from . import *
import yex.font
import yex.document
import yex.parse
import yex.value
import yex.exception
import pytest
import io

def test_get_font_from_name(yex_test_fs):
    font = yex.font.get_font_from_name('cmr10.tfm')
    assert font.filename == 'cmr10.tfm'
    assert font.name == 'cmr10'
    assert font.scale == None

def test_get_font_from_name_setting_scale_dimen(yex_test_fs):

    font = yex.font.get_font_from_name('cmr10.tfm')
    font.scale = yex.value.Dimen(12, "pt")

    assert font.filename == 'cmr10.tfm'
    assert font.name == 'cmr10'
    assert isinstance(font.scale, yex.value.Dimen)
    assert font.scale == yex.value.Dimen(12, "pt")

def test_get_font_from_name_setting_scale_number(yex_test_fs):

    font = yex.font.get_font_from_name('cmr10.tfm')
    font.scale = yex.value.Number(12)

    assert font.filename == 'cmr10.tfm'
    assert font.name == 'cmr10'
    assert isinstance(font.scale, yex.value.Number)
    assert font.scale == 12

def test_font_from_tokens(yex_test_fs):

    string = r"cmr10.tfm"

    with expander_on_string(string) as e:
        font = yex.font.get_font_from_tokens(e)

        assert font.filename == 'cmr10.tfm'
        assert font.name == 'cmr10'
        assert font.scale == None

def test_font_from_tokens_with_scale_dimen(yex_test_fs):

    string = r"cmr10.tfm at 12pt"

    with expander_on_string(string) as e:
        font = yex.font.get_font_from_tokens(e)

        assert font.filename == 'cmr10.tfm'
        assert font.name == 'cmr10'
        assert isinstance(font.scale, yex.value.Dimen)
        assert font.scale == yex.value.Dimen(12, "pt")

def test_font_from_tokens_with_scale_number(yex_test_fs):

    string = r"cmr10.tfm scaled 12"

    with expander_on_string(string) as e:
        font = yex.font.get_font_from_tokens(e)

        assert font.filename == 'cmr10.tfm'
        assert font.name == 'cmr10'
        assert isinstance(font.scale, yex.value.Number)
        assert font.scale == 12

def test_font_used(yex_test_fs):
    font = yex.font.get_font_from_name('cmr10.tfm')
    assert list(font.used)==[]
    font[102] = yex.value.Dimen(12)

    assert font['A'].glyph is not None
    assert list(font.used)==[ord('A')]

    with pytest.raises(yex.exception.YexError):
        font[103] = yex.value.Dimen(12)

def test_font_glyphs(capsys, yex_test_fs):
    font = yex.font.get_font_from_name('cmr10.tfm')

    assert font['A'].glyph is not None

    font['A'].glyph.dump()
    found = capsys.readouterr().out
    expected = ENORMOUS_A
    assert found==expected

def test_font_glyph_image(yex_test_fs):
    font = yex.font.get_font_from_name('cmr10.tfm')
    a = font['A'].glyph.image
    enormous_A = [
            line[6:] for line in
            ENORMOUS_A.split('\n')[1:]
            ]
    for y in range(a.height):
        for x in range(a.width):
            found = a.getpixel((x,y))[3]

            if enormous_A[y][x]=='X':
                expected = 255
            else:
                expected = 0

            assert found==expected, f"{x}, {y}"

def test_get_font_from_name(yex_test_fs):
    for name in [
            'cmr10',
            'cmr10.tfm',
            ]:
        font = yex.font.get_font_from_name(name)
        assert isinstance(font, yex.font.Tfm)

def test_font_identifier(yex_test_fs):

    cmr10 = yex.font.get_font_from_name('cmr10.tfm')
    assert cmr10.identifier == r'\cmr10'

    nullfont = yex.font.Nullfont()
    assert nullfont.identifier == r'\nullfont'

ENORMOUS_A = """Charcode: 65
 00   ..........................XXX..........................
 01   ..........................XXX..........................
 02   ..........................XXX..........................
 03   .........................XXXXX.........................
 04   .........................XXXXX.........................
 05   .........................XXXXX.........................
 06   ........................XXXXXXX........................
 07   ........................XXXXXXX........................
 08   .......................XXXXXXXXX.......................
 09   .......................XXXXXXXXX.......................
 10   .......................XXXXXXXXX.......................
 11   ......................XXXXXXXXXXX......................
 12   ......................XX..XXXXXXX......................
 13   ......................XX..XXXXXXX......................
 14   .....................XXX..XXXXXXXX.....................
 15   .....................XX....XXXXXXX.....................
 16   .....................XX....XXXXXXX.....................
 17   ....................XX.....XXXXXXXX....................
 18   ....................XX......XXXXXXX....................
 19   ....................XX......XXXXXXX....................
 20   ...................XX........XXXXXXX...................
 21   ...................XX........XXXXXXX...................
 22   ...................XX........XXXXXXX...................
 23   ..................XX..........XXXXXXX..................
 24   ..................XX..........XXXXXXX..................
 25   ..................XX..........XXXXXXX..................
 26   .................XX............XXXXXXX.................
 27   .................XX............XXXXXXX.................
 28   .................XX............XXXXXXX.................
 29   ................XX..............XXXXXXX................
 30   ................XX..............XXXXXXX................
 31   ................XX..............XXXXXXX................
 32   ...............XX................XXXXXXX...............
 33   ...............XX................XXXXXXX...............
 34   ..............XXX................XXXXXXXX..............
 35   ..............XX..................XXXXXXX..............
 36   ..............XX..................XXXXXXX..............
 37   .............XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............
 38   .............XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............
 39   .............XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............
 40   ............XXX....................XXXXXXXX............
 41   ............XX......................XXXXXXX............
 42   ............XX......................XXXXXXX............
 43   ...........XX.......................XXXXXXXX...........
 44   ...........XX........................XXXXXXX...........
 45   ...........XX........................XXXXXXX...........
 46   ..........XX..........................XXXXXXX..........
 47   ..........XX..........................XXXXXXX..........
 48   ..........XX..........................XXXXXXX..........
 49   .........XX............................XXXXXXX.........
 50   .........XX............................XXXXXXX.........
 51   .........XX............................XXXXXXX.........
 52   ........XXX.............................XXXXXXX........
 53   .......XXXX.............................XXXXXXX........
 54   ......XXXXXX............................XXXXXXXX.......
 55   ....XXXXXXXXXX........................XXXXXXXXXXX......
 56   XXXXXXXXXXXXXXXXX................XXXXXXXXXXXXXXXXXXXXXX
 57   XXXXXXXXXXXXXXXXX................XXXXXXXXXXXXXXXXXXXXXX
 58   XXXXXXXXXXXXXXXXX................XXXXXXXXXXXXXXXXXXXXXX
"""
