site_name: yex
site_description: typeset beautifully
site_author: Marnanel Thurman
site_url: !ENV READTHEDOCS_CANONICAL_URL

copyright: "(c) 2023-2025 Marnanel Thurman"

repo_name: gitlab
repo_url: https://gitlab.com/marnanel/yex/

theme:
  name: material
  logo: _static/icon.svg
  highlightjs: true
  palette:

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Introduction: index.md
  - How to install Yex: installing.md
  - Controls: controls.md
  - An overview: overview.md
  - Running yex: running.md
  - Logging: logging.md
  - Reference:
     - ref/yex.box.Box.md
     - ref/yex.box.Gismo.md
     - ref/yex.box.Hvbox.md
     - ref/yex.box.Kern.md
     - ref/yex.box.Leader.md
     - ref/yex.box.Rule.md
     - ref/yex.box.Wordbox.md
     - ref/yex.control.Control.md
     - ref/yex.control.Documentfield.md
     - ref/yex.control.Fontsetter.md
     - ref/yex.control.keyword.Arithmetic.md
     - ref/yex.control.keyword.Array.md
     - ref/yex.control.keyword.Box.md
     - ref/yex.control.keyword.Conditional.md
     - ref/yex.control.keyword.Debug.md
     - ref/yex.control.keyword.Documentfield.md
     - ref/yex.control.keyword.Font.md
     - ref/yex.control.keyword.Gismo.md
     - ref/yex.control.keyword.Hyphen.md
     - ref/yex.control.keyword.Input.md
     - ref/yex.control.keyword.Io.md
     - ref/yex.control.keyword.Macro.md
     - ref/yex.control.keyword.Math.md
     - ref/yex.control.keyword.Number.md
     - ref/yex.control.keyword.Other.md
     - ref/yex.control.keyword.Parameter.md
     - ref/yex.control.keyword.Register.md
     - ref/yex.control.keyword.String.md
     - ref/yex.control.keyword.Tab.md
     - ref/yex.control.keyword.Trace.md
     - ref/yex.control.Macro.md
     - ref/yex.control.Parameter.md
     - ref/yex.control.Register.md
     - ref/yex.control.Table.md
     - ref/yex.Decorator.md
     - ref/yex.document.Callframe.md
     - ref/yex.document.Document.md
     - ref/yex.document.Group.md
     - ref/yex.Exception.md
     - ref/yex.Filename.md
     - ref/yex.font.Default.md
     - ref/yex.font.Font.md
     - ref/yex.font.__Main__.md
     - ref/yex.font.Nullfont.md
     - ref/yex.font.Pk.md
     - ref/yex.font.Tfm.md
     - ref/yex.io.Input.md
     - ref/yex.io.Output.md
     - ref/yex.io.Table.md
     - ref/yex.io.Trace.md
     - ref/yex.Logging.md
     - ref/yex.Log.md
     - ref/yex.__Main__.md
     - ref/yex.mode.Horizontal.md
     - ref/yex.mode.Math.md
     - ref/yex.mode.Mode.md
     - ref/yex.mode.Vertical.md
     - ref/yex.output.Html.md
     - ref/yex.output.Null.md
     - ref/yex.output.Output.md
     - ref/yex.output.Svg.md
     - ref/yex.output.Svg_Template.md
     - ref/yex.parse.Afterwards.md
     - ref/yex.parse.Expander.md
     - ref/yex.parse.Location.md
     - ref/yex.parse.Pushback.md
     - ref/yex.parse.Source.md
     - ref/yex.parse.Tokeniser.md
     - ref/yex.parse.Token.md
     - ref/yex.Put.md
     - ref/yex.style.Bare.md
     - ref/yex.style.__Main__.md
     - ref/yex.style.Plain.md
     - ref/yex.style.Style.md
     - ref/yex.Util.md
     - ref/yex.value.Dimen.md
     - ref/yex.value.Glue.md
     - ref/yex.value.Muglue.md
     - ref/yex.value.Number.md
     - ref/yex.value.Tokenlist.md
     - ref/yex.value.Value.md
     - ref/yex.wrap.Dump.md
     - ref/yex.wrap.Fitting.md
     - ref/yex.wrap.Paragraphs.md
     - ref/yex.wrap.Wrapping.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_DOCSTRINGS, true]
      locale: en_GB
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
            line_length: 100
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            skip_local_inventory: true
            merge_init_into_class: true
            annotations_path: full
            show_signature: false
          extensions:
            - fields
  - literate-nav

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: .

extra_javascript:
  - readthedocs.js

docs_dir:
  docs
