site_name: yex
site_description: typeset beautifully
site_author: Marnanel Thurman
site_url: !ENV READTHEDOCS_CANONICAL_URL

copyright: "(c) 2023-2025 Marnanel Thurman"

repo_name: gitlab
repo_url: https://gitlab.com/marnanel/yex/

theme:
  name: material
  logo: _static/icon.svg
  highlightjs: true
  palette:

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Introduction: index.md
  - How to install Yex: installing.md
  - Controls: controls.md
  - An overview: overview.md
  - Running yex: running.md
  - Logging: logging.md
  - Reference:
     - ref/wrap/dump.md
     - ref/wrap/fitting.md
     - ref/wrap/wrapping.md
     - ref/wrap/paragraphs.md
     - ref/util.md
     - ref/document/document.md
     - ref/document/group.md
     - ref/document/callframe.md
     - ref/control/table.md
     - ref/control/fontsetter.md
     - ref/control/parameter.md
     - ref/control/keyword/trace.md
     - ref/control/keyword/array.md
     - ref/control/keyword/tab.md
     - ref/control/keyword/gismo.md
     - ref/control/keyword/definition.md
     - ref/control/keyword/parameter.md
     - ref/control/keyword/io.md
     - ref/control/keyword/conditional.md
     - ref/control/keyword/number.md
     - ref/control/keyword/register.md
     - ref/control/keyword/input.md
     - ref/control/keyword/string.md
     - ref/control/keyword/documentfield.md
     - ref/control/keyword/macro.md
     - ref/control/keyword/font.md
     - ref/control/keyword/debug.md
     - ref/control/keyword/other.md
     - ref/control/keyword/arithmetic.md
     - ref/control/keyword/box.md
     - ref/control/keyword/hyphen.md
     - ref/control/keyword/math.md
     - ref/control/register.md
     - ref/control/documentfield.md
     - ref/control/macro.md
     - ref/control/control.md
     - ref/__main__.md
     - ref/box/rule.md
     - ref/box/gismo.md
     - ref/box/kern.md
     - ref/box/hvbox.md
     - ref/box/box.md
     - ref/box/leader.md
     - ref/box/wordbox.md
     - ref/logging.md
     - ref/io/trace.md
     - ref/io/table.md
     - ref/io/input.md
     - ref/io/output.md
     - ref/exception.md
     - ref/parse/tokeniser.md
     - ref/parse/token.md
     - ref/parse/pushback.md
     - ref/parse/location.md
     - ref/parse/expander.md
     - ref/parse/source.md
     - ref/parse/afterwards.md
     - ref/font/tfm.md
     - ref/font/__main__.md
     - ref/font/default.md
     - ref/font/nullfont.md
     - ref/font/pk.md
     - ref/font/font.md
     - ref/filename.md
     - ref/style/bare.md
     - ref/style/__main__.md
     - ref/style/style.md
     - ref/style/plain.md
     - ref/decorator.md
     - ref/log.md
     - ref/mode/vertical.md
     - ref/mode/mode.md
     - ref/mode/horizontal.md
     - ref/mode/math.md
     - ref/put.md
     - ref/value/tokenlist.md
     - ref/value/number.md
     - ref/value/glue.md
     - ref/value/muglue.md
     - ref/value/dimen.md
     - ref/value/value.md
     - ref/output/svg.md
     - ref/output/html.md
     - ref/output/svg_template.md
     - ref/output/output.md
     - ref/output/null.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_DOCSTRINGS, true]
      locale: en_GB
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
            line_length: 100
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            skip_local_inventory: true
            merge_init_into_class: true
            annotations_path: full
            show_signature: false
          extensions:
            - fields
  - literate-nav

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: .

extra_javascript:
  - readthedocs.js

docs_dir:
  docs
