############# GENERATED CODE - DO NOT EDIT #############

from yex.style.style import Style
class Plain(Style):
    CATCODES = {
          0:  9,         10:  5,         13:  5,         32: 10,
         35:  6,         36:  3,         37: 14,         38:  4,
         65: 11,         66: 11,         67: 11,         68: 11,
         69: 11,         70: 11,         71: 11,         72: 11,
         73: 11,         74: 11,         75: 11,         76: 11,
         77: 11,         78: 11,         79: 11,         80: 11,
         81: 11,         82: 11,         83: 11,         84: 11,
         85: 11,         86: 11,         87: 11,         88: 11,
         89: 11,         90: 11,         92:  0,         94:  7,
         95:  8,         97: 11,         98: 11,         99: 11,
        100: 11,        101: 11,        102: 11,        103: 11,
        104: 11,        105: 11,        106: 11,        107: 11,
        108: 11,        109: 11,        110: 11,        111: 11,
        112: 11,        113: 11,        114: 11,        115: 11,
        116: 11,        117: 11,        118: 11,        119: 11,
        120: 11,        121: 11,        122: 11,        123:  1,
        125:  2,        126: 13,        127: 15,
        }

    MACROS = {

        '\x0c': {'definition': [['\\par']], 'flags': 'outer', 'loc': (0, 20, 41)},
        '\x1a': {'definition': [['\\not'], '='], 'loc': (0, 740, 37)},
        ' ': {'definition': ' ', 'macro': 'space', 'loc': (0, 513, 12)},
        "'": {'definition': ['^', ['\\bgroup'], ['\\prim@s']], 'loc': (0, 735, 30)},
        '\\!': {'definition': [['\\mskip'], '-', ['\\thinmuskip']], 'loc': (0, 733, 14)},
        '\\"': {'definition': ['{', ['\\accent'], '"7F #1}'], 'parameters': 1, 'loc': (0, 704, 10)},
        "\\'": {'definition': ['{', ['\\accent'], '19 #1}'], 'parameters': 1, 'loc': (0, 696, 10)},
        '\\*': {'definition': [['\\discretionary'], '{', ['\\thinspace'], ['\\the'], ['\\textfont'], '2', ['\\char'], '2}{}{}'], 'loc': (0, 734, 22)},
        '\\+': {'definition': [['\\tabalign']], 'flags': 'outer', 'loc': (0, 608, 23)},
        '\\,': {'definition': [['\\mskip'], ['\\thinmuskip']], 'loc': (0, 730, 14)},
        '\\.': {'definition': ['{', ['\\accent'], '95 #1}'], 'parameters': 1, 'loc': (0, 701, 10)},
        '\\;': {'definition': [['\\mskip'], ['\\thickmuskip']], 'loc': (0, 732, 14)},
        '\\=': {'definition': ['{', ['\\accent'], '22 #1}'], 'parameters': 1, 'loc': (0, 699, 10)},
        '\\>': {'definition': [['\\mskip'], ['\\medmuskip']], 'loc': (0, 731, 14)},
        '\\@foot': {'definition': [['\\strut'], ['\\egroup']], 'loc': (0, 1170, 18)},
        '\\@if': {'definition': 'false', 'parameters': [[['\\if@mid']]], 'loc': (0, 268, 15)},
        '\\@ins': {'definition': [['\\par'], ['\\begingroup'], ['\\setbox'], ['\\z@'], ['\\vbox'], ['\\bgroup']], 'loc': (0, 1184, 15)},
        '\\@lign': {'definition': [['\\tabskip'], ['\\z@skip'], ['\\everycr'], '{}'], 'loc': (0, 1125, 20)},
        '\\@nother': {'definition': [['\\dimen@ii'], ['\\dimen@'], ['\\divide'], ['\\dimen@ii'], ['\\count@'], ' ', ['\\setbox'], ['\\tabs'], ['\\hbox'], '{', ['\\hbox'], 'to', ['\\dimen@ii'], '{}', ['\\unhbox'], ['\\tabs'], '}', ['\\advance'], ['\\dimen@'], '-', ['\\dimen@ii'], ['\\advance'], ['\\count@'], ['\\m@ne']], 'loc': (0, 611, 23)},
        '\\@penup': {'definition': [['\\advance'], ['\\lineskip'], ['\\dimen@'], ' ', ['\\advance'], ['\\baselineskip'], ['\\dimen@'], ' ', ['\\advance'], ['\\lineskiplimit'], ['\\dimen@']], 'loc': (0, 1114, 21)},
        '\\@vereq': {'definition': [['\\lower'], '.5', ['\\p@'], ['\\vbox'], '{', ['\\lineskiplimit'], ['\\maxdimen'], ['\\lineskip'], '-.5', ['\\p@'], ' ', ['\\ialign'], '{$', ['\\m@th'], '#1', ['\\hfil'], '##', ['\\hfil'], '$', ['\\crcr'], '#2', ['\\crcr'], '=', ['\\crcr'], '}}'], 'parameters': 2, 'loc': (0, 1043, 23)},
        '\\AA': {'definition': [['\\leavevmode'], ['\\setbox'], '0', ['\\hbox'], '{!}', ['\\dimen@'], ['\\ht'], '0', ['\\advance'], ['\\dimen@'], '-1ex', ['\\rlap'], '{', ['\\raise'], '.67', ['\\dimen@'], ['\\hbox'], '{', ['\\char'], "'27}}A"], 'loc': (0, 668, 20)},
        '\\Arrowvert': {'definition': [['\\delimiter'], '"26B33D '], 'loc': (0, 971, 26)},
        '\\Big': {'definition': ['{', ['\\hbox'], '{$', ['\\left'], '#1', ['\\vbox'], 'to11.5', ['\\p@'], '{}', ['\\right'], '.', ['\\n@space'], '$}}'], 'parameters': 1, 'loc': (0, 1004, 12)},
        '\\Bigg': {'definition': ['{', ['\\hbox'], '{$', ['\\left'], '#1', ['\\vbox'], 'to17.5', ['\\p@'], '{}', ['\\right'], '.', ['\\n@space'], '$}}'], 'parameters': 1, 'loc': (0, 1006, 13)},
        '\\Biggl': {'definition': [['\\mathopen'], ['\\Bigg']], 'loc': (0, 1000, 21)},
        '\\Biggm': {'definition': [['\\mathrel'], ['\\Bigg']], 'loc': (0, 1001, 20)},
        '\\Biggr': {'definition': [['\\mathclose'], ['\\Bigg']], 'loc': (0, 1002, 22)},
        '\\Bigl': {'definition': [['\\mathopen'], ['\\Big']], 'loc': (0, 994, 20)},
        '\\Bigm': {'definition': [['\\mathrel'], ['\\Big']], 'loc': (0, 995, 19)},
        '\\Bigr': {'definition': [['\\mathclose'], ['\\Big']], 'loc': (0, 996, 21)},
        '\\Downarrow': {'definition': [['\\delimiter'], '"322B37F '], 'loc': (0, 979, 26)},
        '\\H': {'definition': ['{', ['\\accent'], '"7D #1}'], 'parameters': 1, 'loc': (0, 702, 10)},
        '\\L': {'definition': [['\\leavevmode'], ['\\setbox'], '0', ['\\hbox'], '{L}', ['\\hbox'], 'to', ['\\wd'], '0{', ['\\hss'], ['\\char'], '32L}'], 'loc': (0, 664, 19)},
        '\\Longleftarrow': {'definition': [['\\Leftarrow'], ['\\joinrel'], ['\\Relbar']], 'loc': (0, 923, 30)},
        '\\Longleftrightarrow': {'definition': [['\\Leftarrow'], ['\\joinrel'], ['\\Rightarrow']], 'loc': (0, 926, 35)},
        '\\Longrightarrow': {'definition': [['\\Relbar'], ['\\joinrel'], ['\\Rightarrow']], 'loc': (0, 920, 28)},
        '\\Orb': {'definition': [['\\mathhexbox'], '20D'], 'loc': (0, 677, 21)},
        '\\P': {'definition': [['\\mathhexbox'], '27B'], 'loc': (0, 676, 19)},
        '\\Pr': {'definition': [['\\mathop'], '{', ['\\rm'], 'Pr}'], 'loc': (0, 1083, 16)},
        '\\Relbar': {'definition': [['\\mathrel'], '='], 'loc': (0, 915, 21)},
        '\\S': {'definition': [['\\mathhexbox'], '278'], 'loc': (0, 675, 19)},
        '\\TeX': {'definition': ['T', ['\\kern'], '-.1667em', ['\\lower'], '.5ex', ['\\hbox'], '{E}', ['\\kern'], '-.125emX'], 'loc': (0, 693, 10)},
        '\\Uparrow': {'definition': [['\\delimiter'], '"322A37E '], 'loc': (0, 978, 24)},
        '\\Updownarrow': {'definition': [['\\delimiter'], '"326D377 '], 'loc': (0, 980, 28)},
        '\\Vert': {'definition': [['\\delimiter'], '"26B30D '], 'loc': (0, 973, 21)},
        '\\\\': {'definition': '#1', 'parameters': [[], [[12, 'p'], [12, 't']]], 'loc': (0, 682, 42)},
        '\\^': {'definition': ['{', ['\\accent'], '94 #1}'], 'parameters': 1, 'loc': (0, 700, 10)},
        '\\^D': {'definition': ['{', ['\\accent'], '94 #1}'], 'macro': '^', 'parameters': 1, 'loc': (0, 700, 10)},
        '\\^I': {'definition': [['\\ ']], 'loc': (0, 506, 11)},
        '\\^M': {'definition': [['\\ ']], 'loc': (0, 505, 11)},
        '\\^S': {'definition': ['{', ['\\accent'], '21 #1}'], 'macro': 'u', 'parameters': 1, 'loc': (0, 698, 10)},
        '\\^_': {'definition': ['{', ['\\accent'], '20 #1}'], 'macro': 'v', 'parameters': 1, 'loc': (0, 697, 10)},
        '\\_': {'definition': [['\\leavevmode'], ['\\kern'], '.06em ', ['\\vbox'], '{', ['\\hrule'], 'width.3em}'], 'loc': (0, 667, 20)},
        '\\`': {'definition': ['{', ['\\accent'], '18 #1}'], 'parameters': 1, 'loc': (0, 695, 10)},
        '\\aa': {'definition': [['\\accent'], '23a'], 'loc': (0, 662, 16)},
        '\\acute': {'definition': [['\\mathaccent'], '"7013 '], 'loc': (0, 939, 23)},
        '\\advancepageno': {'definition': [['\\ifnum'], ['\\pageno'], '<', ['\\z@'], ['\\global'], ['\\advance'], ['\\pageno'], ['\\m@ne'], ' ', ['\\else'], ['\\global'], ['\\advance'], ['\\pageno'], ['\\@ne'], ['\\fi']], 'loc': (0, 1153, 26)},
        '\\alloc@': {'definition': [['\\global'], ['\\advance'], ['\\count'], '1#1by', ['\\@ne'], ' ', ['\\ch@ck'], '#1#4#2', ['\\allocationnumber'], '=', ['\\count'], '1#1', ['\\global'], '#3#5=', ['\\allocationnumber'], ' ', ['\\wlog'], '{', ['\\string'], '#5=', ['\\string'], '#2', ['\\the'], ['\\allocationnumber'], '}'], 'parameters': 5, 'loc': (0, 237, 30)},
        '\\allowbreak': {'definition': [['\\penalty'], ['\\z@']], 'loc': (0, 560, 26)},
        '\\angle': {'definition': ['{', ['\\vbox'], '{', ['\\ialign'], '{$', ['\\m@th'], ['\\scriptstyle'], '##$', ['\\crcr'], ' ', ['\\not'], ['\\mathrel'], '{', ['\\mkern'], '14mu}', ['\\crcr'], ' ', ['\\noalign'], '{', ['\\nointerlineskip'], '} ', ['\\mkern'], '2.5mu', ['\\leaders'], ['\\hrule'], 'height.34pt', ['\\hfill'], ['\\mkern'], '2.5mu', ['\\crcr'], '}}}'], 'loc': (0, 801, 12)},
        '\\arccos': {'definition': [['\\mathop'], '{', ['\\rm'], 'arccos}', ['\\nolimits']], 'loc': (0, 1064, 20)},
        '\\arcsin': {'definition': [['\\mathop'], '{', ['\\rm'], 'arcsin}', ['\\nolimits']], 'loc': (0, 1061, 20)},
        '\\arctan': {'definition': [['\\mathop'], '{', ['\\rm'], 'arctan}', ['\\nolimits']], 'loc': (0, 1067, 20)},
        '\\arg': {'definition': [['\\mathop'], '{', ['\\rm'], 'arg}', ['\\nolimits']], 'loc': (0, 1077, 17)},
        '\\arrowvert': {'definition': [['\\delimiter'], '"26A33C '], 'loc': (0, 970, 26)},
        '\\b': {'definition': ['{', ['\\o@lign'], '{', ['\\relax'], '#1', ['\\crcr'], ['\\hidewidth'], ['\\sh@ft'], '{-3ex}', ['\\vbox'], 'to.2ex{', ['\\hbox'], '{', ['\\char'], '22}', ['\\vss'], '}', ['\\hidewidth'], '}}'], 'parameters': 1, 'loc': (0, 686, 10)},
        '\\backslash': {'definition': [['\\delimiter'], '"26E30F '], 'loc': (0, 981, 26)},
        '\\bar': {'definition': [['\\mathaccent'], '"7016 '], 'loc': (0, 943, 21)},
        '\\beginsection': {'definition': [['\\vskip'], ['\\z@'], 'plus.3', ['\\vsize'], ['\\penalty'], '-250 ', ['\\vskip'], ['\\z@'], 'plus-.3', ['\\vsize'], ['\\bigskip'], ['\\vskip'], ['\\parskip'], ' ', ['\\message'], '{#1}', ['\\leftline'], '{', ['\\bf'], '#1}', ['\\nobreak'], ['\\smallskip'], ['\\noindent']], 'flags': 'outer', 'parameters': [[], [['\\par']]], 'loc': (0, 640, 37)},
        '\\bf': {'definition': [['\\fam'], ['\\bffam'], ['\\tenbf']], 'loc': (0, 488, 27)},
        '\\big': {'definition': ['{', ['\\hbox'], '{$', ['\\left'], '#1', ['\\vbox'], 'to8.5', ['\\p@'], '{}', ['\\right'], '.', ['\\n@space'], '$}}'], 'parameters': 1, 'loc': (0, 1003, 12)},
        '\\bigbreak': {'definition': [['\\par'], ['\\ifdim'], ['\\lastskip'], '<', ['\\bigskipamount'], ' ', ['\\removelastskip'], ['\\penalty'], '-200', ['\\bigskip'], ['\\fi']], 'loc': (0, 572, 19)},
        '\\bigg': {'definition': ['{', ['\\hbox'], '{$', ['\\left'], '#1', ['\\vbox'], 'to14.5', ['\\p@'], '{}', ['\\right'], '.', ['\\n@space'], '$}}'], 'parameters': 1, 'loc': (0, 1005, 13)},
        '\\biggl': {'definition': [['\\mathopen'], ['\\bigg']], 'loc': (0, 997, 21)},
        '\\biggm': {'definition': [['\\mathrel'], ['\\bigg']], 'loc': (0, 998, 20)},
        '\\biggr': {'definition': [['\\mathclose'], ['\\bigg']], 'loc': (0, 999, 22)},
        '\\bigl': {'definition': [['\\mathopen'], ['\\big']], 'loc': (0, 991, 20)},
        '\\bigm': {'definition': [['\\mathrel'], ['\\big']], 'loc': (0, 992, 19)},
        '\\bigr': {'definition': [['\\mathclose'], ['\\big']], 'loc': (0, 993, 21)},
        '\\bigskip': {'definition': [['\\vskip'], ['\\bigskipamount']], 'loc': (0, 541, 20)},
        '\\bmod': {'definition': [['\\nonscript'], ['\\mskip'], '-', ['\\medmuskip'], ['\\mkern'], '5mu ', ['\\mathbin'], '{', ['\\rm'], 'mod}', ['\\penalty'], '900', ['\\mkern'], '5mu', ['\\nonscript'], ['\\mskip'], '-', ['\\medmuskip']], 'loc': (0, 1087, 21)},
        '\\bordermatrix': {'definition': [['\\begingroup'], ['\\m@th'], ' ', ['\\setbox'], ['\\z@'], ['\\vbox'], '{', ['\\def'], ['\\cr'], '{', ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '2', ['\\p@'], ['\\global'], ['\\let'], ['\\cr'], ['\\endline'], '}}', ['\\ialign'], '{$##$', ['\\hfil'], ['\\kern'], '2', ['\\p@'], ['\\kern'], ['\\p@renwd'], '&', ['\\thinspace'], ['\\hfil'], '$##$', ['\\hfil'], ' &&', ['\\quad'], ['\\hfil'], '$##$', ['\\hfil'], ['\\crcr'], ' ', ['\\omit'], ['\\strut'], ['\\hfil'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '-', ['\\baselineskip'], '}#1', ['\\crcr'], ['\\omit'], ['\\strut'], ['\\cr'], '}}', ['\\setbox'], ['\\tw@'], ['\\vbox'], '{', ['\\unvcopy'], ['\\z@'], ['\\global'], ['\\setbox'], ['\\@ne'], ['\\lastbox'], '}', ['\\setbox'], ['\\tw@'], ['\\hbox'], '{', ['\\unhbox'], ['\\@ne'], ['\\unskip'], ['\\global'], ['\\setbox'], ['\\@ne'], ['\\lastbox'], '}', ['\\setbox'], ['\\tw@'], ['\\hbox'], '{$', ['\\kern'], ['\\wd'], ['\\@ne'], ['\\kern'], '-', ['\\p@renwd'], ['\\left'], '(', ['\\kern'], '-', ['\\wd'], ['\\@ne'], ' ', ['\\global'], ['\\setbox'], ['\\@ne'], ['\\vbox'], '{', ['\\box'], ['\\@ne'], ['\\kern'], '2', ['\\p@'], '}', ['\\vcenter'], '{', ['\\kern'], '-', ['\\ht'], ['\\@ne'], ['\\unvbox'], ['\\z@'], ['\\kern'], '-', ['\\baselineskip'], '}', ['\\,'], ['\\right'], ')$}', ['\\null'], ['\\;'], ['\\vbox'], '{', ['\\kern'], ['\\ht'], ['\\@ne'], ['\\box'], ['\\tw@'], '}', ['\\endgroup']], 'parameters': 1, 'loc': (0, 1100, 33)},
        '\\bowtie': {'definition': [['\\mathrel'], ['\\triangleright'], ['\\joinrel'], ['\\mathrel'], ['\\triangleleft']], 'loc': (0, 918, 21)},
        '\\brace': {'definition': [['\\atopwithdelims'], ['\\{'], ['\\}']], 'loc': (0, 1011, 27)},
        '\\bracevert': {'definition': [['\\delimiter'], '"77C33E '], 'loc': (0, 972, 26)},
        '\\brack': {'definition': [['\\atopwithdelims'], '[]'], 'loc': (0, 1010, 27)},
        '\\break': {'definition': [['\\penalty'], '-', ['\\@M']], 'loc': (0, 558, 20)},
        '\\breve': {'definition': [['\\mathaccent'], '"7015 '], 'loc': (0, 944, 23)},
        '\\buildrel': {'definition': [['\\mathrel'], '{', ['\\mathop'], '{', ['\\kern'], ['\\z@'], '#2}', ['\\limits'], '^{#1}}'], 'parameters': [[], [['\\over']], []], 'loc': (0, 1051, 32)},
        '\\bye': {'definition': [['\\par'], ['\\vfill'], ['\\supereject'], ['\\end']], 'flags': 'outer', 'loc': (0, 724, 20)},
        '\\c': {'definition': ['{', ['\\setbox'], ['\\z@'], ['\\hbox'], '{#1}', ['\\ifdim'], ['\\ht'], ['\\z@'], '=1ex', ['\\accent'], '24 #1', ['\\else'], ['\\ooalign'], '{', ['\\unhbox'], ['\\z@'], ['\\crcr'], ['\\hidewidth'], ['\\char'], '24', ['\\hidewidth'], '}', ['\\fi'], '}'], 'parameters': 1, 'loc': (0, 688, 10)},
        '\\c@ncel': {'definition': [['\\m@th'], ['\\ooalign'], '{$', ['\\hfil'], '#1', ['\\mkern'], '1mu/', ['\\hfil'], '$', ['\\crcr'], '$#1#2$}'], 'parameters': 2, 'loc': (0, 1046, 22)},
        '\\cal': {'definition': [['\\fam'], ['\\tw@']], 'loc': (0, 482, 14)},
        '\\cases': {'definition': [['\\left'], ['\\{'], ['\\,'], ['\\vcenter'], '{', ['\\normalbaselines'], ['\\m@th'], ' ', ['\\ialign'], '{$##', ['\\hfil'], '$&', ['\\quad'], '##', ['\\hfil'], ['\\crcr'], '#1', ['\\crcr'], '}}', ['\\right'], '.'], 'parameters': 1, 'loc': (0, 1091, 19)},
        '\\cdots': {'definition': [['\\mathinner'], '{', ['\\cdotp'], ['\\cdotp'], ['\\cdotp'], '}'], 'loc': (0, 933, 22)},
        '\\centerline': {'definition': [['\\line'], '{', ['\\hss'], '#1', ['\\hss'], '}'], 'parameters': 1, 'loc': (0, 578, 24)},
        '\\ch@ck': {'definition': [['\\ifnum'], ['\\count'], '1#1<#2', ['\\else'], ['\\errmessage'], '{No room for a new #3}', ['\\fi']], 'parameters': 3, 'loc': (0, 250, 24)},
        '\\check': {'definition': [['\\mathaccent'], '"7014 '], 'loc': (0, 945, 23)},
        '\\choose': {'definition': [['\\atopwithdelims'], '()'], 'loc': (0, 1009, 28)},
        '\\cleartabs': {'definition': [['\\global'], ['\\setbox'], ['\\tabsyet'], ['\\null'], ['\\setbox'], ['\\tabs'], ['\\null']], 'loc': (0, 601, 23)},
        '\\cong': {'definition': [['\\mathrel'], '{', ['\\mathpalette'], ['\\@vereq'], ['\\sim'], '}'], 'loc': (0, 1042, 19)},
        '\\copyright': {'definition': ['{', ['\\ooalign'], '{', ['\\hfil'], ['\\raise'], '.07ex', ['\\hbox'], '{c}', ['\\hfil'], ['\\crcr'], ['\\Orb'], '}}'], 'loc': (0, 690, 16)},
        '\\cos': {'definition': [['\\mathop'], '{', ['\\rm'], 'cos}', ['\\nolimits']], 'loc': (0, 1063, 17)},
        '\\cosh': {'definition': [['\\mathop'], '{', ['\\rm'], 'cosh}', ['\\nolimits']], 'loc': (0, 1065, 18)},
        '\\cot': {'definition': [['\\mathop'], '{', ['\\rm'], 'cot}', ['\\nolimits']], 'loc': (0, 1069, 17)},
        '\\coth': {'definition': [['\\mathop'], '{', ['\\rm'], 'coth}', ['\\nolimits']], 'loc': (0, 1070, 18)},
        '\\csc': {'definition': [['\\mathop'], '{', ['\\rm'], 'csc}', ['\\nolimits']], 'loc': (0, 1072, 17)},
        '\\d': {'definition': ['{', ['\\o@lign'], '{', ['\\relax'], '#1', ['\\crcr'], ['\\hidewidth'], ['\\sh@ft'], '{-1ex}.', ['\\hidewidth'], '}}'], 'parameters': 1, 'loc': (0, 685, 10)},
        '\\dag': {'definition': [['\\mathhexbox'], '279'], 'loc': (0, 673, 21)},
        '\\ddag': {'definition': [['\\mathhexbox'], '27A'], 'loc': (0, 674, 22)},
        '\\ddot': {'definition': [['\\mathaccent'], '"707F '], 'loc': (0, 941, 22)},
        '\\ddots': {'definition': [['\\mathinner'], '{', ['\\mkern'], '1mu', ['\\raise'], '7', ['\\p@'], ['\\vbox'], '{', ['\\kern'], '7', ['\\p@'], ['\\hbox'], '{.}}', ['\\mkern'], '2mu ', ['\\raise'], '4', ['\\p@'], ['\\hbox'], '{.}', ['\\mkern'], '2mu', ['\\raise'], ['\\p@'], ['\\hbox'], '{.}', ['\\mkern'], '1mu}'], 'loc': (0, 936, 22)},
        '\\deg': {'definition': [['\\mathop'], '{', ['\\rm'], 'deg}', ['\\nolimits']], 'loc': (0, 1085, 17)},
        '\\det': {'definition': [['\\mathop'], '{', ['\\rm'], 'det}'], 'loc': (0, 1081, 17)},
        '\\dim': {'definition': [['\\mathop'], '{', ['\\rm'], 'dim}', ['\\nolimits']], 'loc': (0, 1079, 17)},
        '\\displ@y': {'definition': [['\\global'], ['\\dt@ptrue'], ['\\openup'], ['\\jot'], ['\\m@th'], ' ', ['\\everycr'], '{', ['\\noalign'], '{', ['\\ifdt@p'], ['\\global'], ['\\dt@pfalse'], ['\\ifdim'], ['\\prevdepth'], '>-1000', ['\\p@'], ' ', ['\\vskip'], '-', ['\\lineskiplimit'], ['\\vskip'], ['\\normallineskiplimit'], ['\\fi'], ' ', ['\\else'], ['\\penalty'], ['\\interdisplaylinepenalty'], ['\\fi'], '}}'], 'loc': (0, 1121, 21)},
        '\\displaylines': {'definition': [['\\displ@y'], ['\\tabskip'], ['\\z@skip'], ' ', ['\\halign'], '{', ['\\hbox'], 'to', ['\\displaywidth'], '{$', ['\\@lign'], ['\\hfil'], ['\\displaystyle'], '##', ['\\hfil'], '$}', ['\\crcr'], ' #1', ['\\crcr'], '}'], 'parameters': 1, 'loc': (0, 1126, 30)},
        '\\dospecials': {'definition': [['\\do'], ['\\ '], ['\\do'], ['\\\\'], ['\\do'], ['\\{'], ['\\do'], ['\\}'], ['\\do'], ['\\$'], ['\\do'], ['\\&'], ['\\do'], ['\\#'], ['\\do'], ['\\^'], ['\\do'], ['\\^K'], ['\\do'], ['\\_'], ['\\do'], ['\\^A'], ['\\do'], ['\\%'], ['\\do'], ['\\~']], 'loc': (0, 39, 20)},
        '\\dosupereject': {'definition': [['\\ifnum'], ['\\insertpenalties'], '>', ['\\z@'], ['\\line'], '{}', ['\\kern'], '-', ['\\topskip'], ['\\nobreak'], ['\\vfill'], ['\\supereject'], ['\\fi']], 'loc': (0, 1205, 25)},
        '\\dot': {'definition': [['\\mathaccent'], '"705F '], 'loc': (0, 948, 21)},
        '\\doteq': {'definition': [['\\buildrel'], ['\\textstyle'], '.', ['\\over'], '='], 'loc': (0, 1052, 21)},
        '\\dotfill': {'definition': [['\\cleaders'], ['\\hbox'], '{$', ['\\m@th'], ['\\mkern'], '1.5mu.', ['\\mkern'], '1.5mu$}', ['\\hfill']], 'loc': (0, 708, 23)},
        '\\dots': {'definition': [['\\relax'], ['\\ifmmode'], ['\\ldots'], ['\\else'], '$', ['\\m@th'], ['\\ldots'], ['\\,'], '$', ['\\fi']], 'loc': (0, 692, 17)},
        '\\downarrow': {'definition': [['\\delimiter'], '"3223379 '], 'loc': (0, 976, 26)},
        '\\downbracefill': {'definition': ['$', ['\\m@th'], ['\\setbox'], ['\\z@'], ['\\hbox'], '{$', ['\\braceld'], '$}', ['\\braceld'], ['\\leaders'], ['\\vrule'], 'height', ['\\ht'], ['\\z@'], 'depth', ['\\z@'], ['\\hfill'], ['\\braceru'], ' ', ['\\bracelu'], ['\\leaders'], ['\\vrule'], 'height', ['\\ht'], ['\\z@'], 'depth', ['\\z@'], ['\\hfill'], ['\\bracerd'], '$'], 'loc': (0, 717, 20)},
        '\\eject': {'definition': [['\\par'], ['\\break']], 'loc': (0, 564, 16)},
        '\\empty': {'definition': []},
        '\\endinsert': {'definition': [['\\egroup'], ['\\if@mid'], ['\\dimen@'], ['\\ht'], ['\\z@'], ['\\advance'], ['\\dimen@'], ['\\dp'], ['\\z@'], ['\\advance'], ['\\dimen@'], '12', ['\\p@'], ' ', ['\\advance'], ['\\dimen@'], ['\\pagetotal'], ['\\advance'], ['\\dimen@'], '-', ['\\pageshrink'], ' ', ['\\ifdim'], ['\\dimen@'], '>', ['\\pagegoal'], ['\\@midfalse'], ['\\p@gefalse'], ['\\fi'], ['\\fi'], ' ', ['\\if@mid'], ['\\bigskip'], ['\\box'], ['\\z@'], ['\\bigbreak'], ' ', ['\\else'], ['\\insert'], ['\\topins'], '{', ['\\penalty'], '100 ', ['\\splittopskip'], ['\\z@skip'], ' ', ['\\splitmaxdepth'], ['\\maxdimen'], ['\\floatingpenalty'], ['\\z@'], ' ', ['\\ifp@ge'], ['\\dimen@'], ['\\dp'], ['\\z@'], ' ', ['\\vbox'], 'to', ['\\vsize'], '{', ['\\unvbox'], ['\\z@'], ['\\kern'], '-', ['\\dimen@'], '}', ['\\else'], ['\\box'], ['\\z@'], ['\\nobreak'], ['\\bigskip'], ['\\fi'], '}', ['\\fi'], ['\\endgroup']], 'loc': (0, 1185, 24)},
        '\\enskip': {'definition': [['\\hskip'], '.5em', ['\\relax']], 'loc': (0, 535, 19)},
        '\\enspace': {'definition': [['\\kern'], '.5em '], 'loc': (0, 533, 19)},
        '\\eqalign': {'definition': [['\\null'], ['\\,'], ['\\vcenter'], '{', ['\\openup'], ['\\jot'], ['\\m@th'], ' ', ['\\ialign'], '{', ['\\strut'], ['\\hfil'], '$', ['\\displaystyle'], '{##}$&$', ['\\displaystyle'], '{{}##}$', ['\\hfil'], ' ', ['\\crcr'], '#1', ['\\crcr'], '}}', ['\\,']], 'parameters': 1, 'loc': (0, 1117, 21)},
        '\\eqalignno': {'definition': [['\\displ@y'], ['\\tabskip'], ['\\centering'], ' ', ['\\halign'], 'to', ['\\displaywidth'], '{', ['\\hfil'], '$', ['\\@lign'], ['\\displaystyle'], '{##}$', ['\\tabskip'], ['\\z@skip'], ' &$', ['\\@lign'], ['\\displaystyle'], '{{}##}$', ['\\hfil'], ['\\tabskip'], ['\\centering'], ' &', ['\\llap'], '{$', ['\\@lign'], '##$}', ['\\tabskip'], ['\\z@skip'], ['\\crcr'], ' #1', ['\\crcr'], '}'], 'parameters': 1, 'loc': (0, 1129, 27)},
        '\\exp': {'definition': [['\\mathop'], '{', ['\\rm'], 'exp}', ['\\nolimits']], 'loc': (0, 1082, 17)},
        '\\f@@t': {'definition': [['\\bgroup'], ['\\aftergroup'], ['\\@foot'], ['\\let'], ['\\next']], 'loc': (0, 1168, 18)},
        '\\f@t': {'definition': ['#1', ['\\@foot']], 'parameters': 1, 'loc': (0, 1169, 12)},
        '\\filbreak': {'definition': [['\\par'], ['\\vfil'], ['\\penalty'], '-200', ['\\vfilneg']], 'loc': (0, 562, 19)},
        '\\finph@nt': {'definition': [['\\setbox'], ['\\tw@'], ['\\null'], ' ', ['\\ifv@'], ['\\ht'], ['\\tw@'], ['\\ht'], ['\\z@'], ['\\dp'], ['\\tw@'], ['\\dp'], ['\\z@'], ['\\fi'], ' ', ['\\ifh@'], ['\\wd'], ['\\tw@'], ['\\wd'], ['\\z@'], ['\\fi'], ['\\box'], ['\\tw@']], 'loc': (0, 1031, 22)},
        '\\finsm@sh': {'definition': [['\\ht'], ['\\z@'], ['\\z@'], ['\\dp'], ['\\z@'], ['\\z@'], ['\\box'], ['\\z@']], 'loc': (0, 1040, 18)},
        '\\fmtname': {'definition': 'plain', 'loc': (0, 1241, 14)},
        '\\fmtversion': {'definition': '3.141592653', 'loc': (0, 1241, 36)},
        '\\fo@t': {'definition': [['\\ifcat'], ['\\bgroup'], ['\\noexpand'], ['\\next'], ['\\let'], ['\\next'], ['\\f@@t'], ' ', ['\\else'], ['\\let'], ['\\next'], ['\\f@t'], ['\\fi'], ['\\next']], 'loc': (0, 1166, 17)},
        '\\folio': {'definition': [['\\ifnum'], ['\\pageno'], '<', ['\\z@'], ['\\romannumeral'], '-', ['\\pageno'], ['\\else'], ['\\number'], ['\\pageno'], ['\\fi']], 'loc': (0, 1151, 18)},
        '\\footnote': {'definition': [['\\let'], ['\\@sf'], ['\\empty'], ['\\ifhmode'], ['\\edef'], ['\\@sf'], '{', ['\\spacefactor'], ['\\the'], ['\\spacefactor'], '}', ['\\/'], ['\\fi'], ' #1', ['\\@sf'], ['\\vfootnote'], '{#1}'], 'parameters': 1, 'loc': (0, 1157, 21)},
        '\\footnoterule': {'definition': [['\\kern'], '-3', ['\\p@'], ' ', ['\\hrule'], 'width 2truein ', ['\\kern'], '2.6', ['\\p@']], 'loc': (0, 1215, 24)},
        '\\footstrut': {'definition': [['\\vbox'], 'to', ['\\splittopskip'], '{}'], 'loc': (0, 1171, 22)},
        '\\frenchspacing': {'definition': [['\\sfcode'], '`', ['\\.'], ['\\@m'], ['\\sfcode'], '`', ['\\?'], ['\\@m'], ['\\sfcode'], '`', ['\\!'], ['\\@m'], ' ', ['\\sfcode'], '`', ['\\:'], ['\\@m'], ['\\sfcode'], '`', ['\\;'], ['\\@m'], ['\\sfcode'], '`', ['\\,'], ['\\@m']], 'loc': (0, 497, 27)},
        '\\gcd': {'definition': [['\\mathop'], '{', ['\\rm'], 'gcd}'], 'loc': (0, 1084, 17)},
        '\\getf@ctor': {'definition': '#1', 'macro': '\\', 'parameters': [[], [[12, 'p'], [12, 't']]], 'loc': (0, 682, 42)},
        '\\goodbreak': {'definition': [['\\par'], ['\\penalty'], '-500 '], 'loc': (0, 563, 20)},
        '\\grave': {'definition': [['\\mathaccent'], '"7012 '], 'loc': (0, 940, 23)},
        '\\hang': {'definition': [['\\hangindent'], ['\\parindent']], 'loc': (0, 633, 22)},
        '\\hat': {'definition': [['\\mathaccent'], '"705E '], 'loc': (0, 946, 21)},
        '\\hbar': {'definition': ['{', ['\\mathchar'], "'26", ['\\mkern'], '-9muh}'], 'loc': (0, 786, 11)},
        '\\hgl@': {'definition': [['\\leavevmode'], ['\\count@'], ['\\spacefactor'], ['\\vrule'], 'width', ['\\z@'], ' ', ['\\nobreak'], ['\\hskip'], ['\\skip@'], ['\\spacefactor'], ['\\count@']], 'loc': (0, 552, 23)},
        '\\hglue': {'definition': [['\\afterassignment'], ['\\hgl@'], ['\\skip@'], '='], 'loc': (0, 551, 28)},
        '\\hidewidth': {'definition': [['\\hskip'], ['\\hideskip']], 'loc': (0, 591, 22)},
        '\\hom': {'definition': [['\\mathop'], '{', ['\\rm'], 'hom}', ['\\nolimits']], 'loc': (0, 1080, 17)},
        '\\hookleftarrow': {'definition': [['\\leftarrow'], ['\\joinrel'], ['\\rhook']], 'loc': (0, 917, 55)},
        '\\hookrightarrow': {'definition': [['\\lhook'], ['\\joinrel'], ['\\rightarrow']], 'loc': (0, 916, 52)},
        '\\hphantom': {'definition': [['\\v@false'], ['\\h@true'], ['\\ph@nt']], 'loc': (0, 1025, 23)},
        '\\hrulefill': {'definition': [['\\leaders'], ['\\hrule'], ['\\hfill']], 'loc': (0, 707, 24)},
        '\\ialign': {'definition': [['\\everycr'], '{}', ['\\tabskip'], ['\\z@skip'], ['\\halign']], 'loc': (0, 592, 21)},
        '\\if@': {'definition': [], 'parameters': [[[12, 'i'], [12, 'f']]]},
        '\\iff': {'definition': [['\\;'], ['\\Longleftrightarrow'], ['\\;']], 'loc': (0, 927, 11)},
        '\\inf': {'definition': [['\\mathop'], '{', ['\\rm'], 'inf}'], 'loc': (0, 1076, 17)},
        '\\int': {'definition': [['\\intop'], ['\\nolimits']], 'loc': (0, 823, 41)},
        '\\it': {'definition': [['\\fam'], ['\\itfam'], ['\\tenit']], 'loc': (0, 484, 27)},
        '\\item': {'definition': [['\\par'], ['\\hang'], ['\\textindent']], 'loc': (0, 635, 15)},
        '\\itemitem': {'definition': [['\\par'], ['\\indent'], ['\\hangindent'], '2', ['\\parindent'], ['\\textindent']], 'loc': (0, 636, 19)},
        '\\iterate': {'definition': [['\\body'], ['\\let'], ['\\next'], ['\\iterate'], ['\\else'], ['\\let'], ['\\next'], ['\\relax'], ['\\fi'], ['\\next']], 'loc': (0, 528, 20)},
        '\\joinrel': {'definition': [['\\mathrel'], '{', ['\\mkern'], '-3mu}'], 'loc': (0, 913, 22)},
        '\\ker': {'definition': [['\\mathop'], '{', ['\\rm'], 'ker}', ['\\nolimits']], 'loc': (0, 1078, 17)},
        '\\l': {'definition': [['\\char'], '32l'], 'loc': (0, 663, 13)},
        '\\langle': {'definition': [['\\delimiter'], '"426830A '], 'loc': (0, 983, 23)},
        '\\lbrace': {'definition': [['\\delimiter'], '"4266308 '], 'loc': (0, 985, 23)},
        '\\lbrack': {'definition': '[', 'loc': (0, 509, 13)},
        '\\lceil': {'definition': [['\\delimiter'], '"4264306 '], 'loc': (0, 987, 22)},
        '\\ldots': {'definition': [['\\mathinner'], '{', ['\\ldotp'], ['\\ldotp'], ['\\ldotp'], '}'], 'loc': (0, 932, 22)},
        '\\leavevmode': {'definition': [['\\unhbox'], ['\\voidb@x']], 'loc': (0, 666, 24)},
        '\\leftarrowfill': {'definition': ['$', ['\\m@th'], ['\\mathord'], ['\\leftarrow'], ['\\mkern'], '-7mu', ['\\cleaders'], ['\\hbox'], '{$', ['\\mkern'], '-2mu', ['\\smash'], '-', ['\\mkern'], '-2mu$}', ['\\hfill'], ' ', ['\\mkern'], '-7mu', ['\\smash'], '-$'], 'loc': (0, 712, 20)},
        '\\leftline': {'definition': [['\\line'], '{#1', ['\\hss'], '}'], 'parameters': 1, 'loc': (0, 576, 22)},
        '\\leqalignno': {'definition': [['\\displ@y'], ['\\tabskip'], ['\\centering'], ' ', ['\\halign'], 'to', ['\\displaywidth'], '{', ['\\hfil'], '$', ['\\@lign'], ['\\displaystyle'], '{##}$', ['\\tabskip'], ['\\z@skip'], ' &$', ['\\@lign'], ['\\displaystyle'], '{{}##}$', ['\\hfil'], ['\\tabskip'], ['\\centering'], ' &', ['\\kern'], '-', ['\\displaywidth'], ['\\rlap'], '{$', ['\\@lign'], '##$}', ['\\tabskip'], ['\\displaywidth'], ['\\crcr'], ' #1', ['\\crcr'], '}'], 'parameters': 1, 'loc': (0, 1134, 28)},
        '\\lfloor': {'definition': [['\\delimiter'], '"4262304 '], 'loc': (0, 989, 23)},
        '\\lg': {'definition': [['\\mathop'], '{', ['\\rm'], 'lg}', ['\\nolimits']], 'loc': (0, 1055, 16)},
        '\\lgroup': {'definition': [['\\delimiter'], '"462833A '], 'loc': (0, 968, 23)},
        '\\lim': {'definition': [['\\mathop'], '{', ['\\rm'], 'lim}'], 'loc': (0, 1057, 17)},
        '\\liminf': {'definition': [['\\mathop'], '{', ['\\rm'], 'lim', ['\\,'], 'inf}'], 'loc': (0, 1059, 20)},
        '\\limsup': {'definition': [['\\mathop'], '{', ['\\rm'], 'lim', ['\\,'], 'sup}'], 'loc': (0, 1058, 20)},
        '\\line': {'definition': [['\\hbox'], 'to', ['\\hsize']], 'loc': (0, 575, 17)},
        '\\llap': {'definition': [['\\hbox'], 'to', ['\\z@'], '{', ['\\hss'], '#1}'], 'parameters': 1, 'loc': (0, 581, 19)},
        '\\lmoustache': {'definition': [['\\delimiter'], '"437A340 '], 'loc': (0, 966, 27)},
        '\\ln': {'definition': [['\\mathop'], '{', ['\\rm'], 'ln}', ['\\nolimits']], 'loc': (0, 1056, 16)},
        '\\log': {'definition': [['\\mathop'], '{', ['\\rm'], 'log}', ['\\nolimits']], 'loc': (0, 1054, 17)},
        '\\loggingall': {'definition': [['\\tracingcommands'], ['\\tw@'], ['\\tracingstats'], ['\\tw@'], ' ', ['\\tracingpages'], ['\\@ne'], ['\\tracingoutput'], ['\\@ne'], ['\\tracinglostchars'], ['\\@ne'], ' ', ['\\tracingmacros'], ['\\tw@'], ['\\tracingparagraphs'], ['\\@ne'], ['\\tracingrestores'], ['\\@ne'], ' ', ['\\showboxbreadth'], ['\\maxdimen'], ['\\showboxdepth'], ['\\maxdimen']], 'loc': (0, 1228, 33)},
        '\\longleftarrow': {'definition': [['\\leftarrow'], ['\\joinrel'], ['\\relbar']], 'loc': (0, 922, 30)},
        '\\longleftrightarrow': {'definition': [['\\leftarrow'], ['\\joinrel'], ['\\rightarrow']], 'loc': (0, 925, 35)},
        '\\longmapsto': {'definition': [['\\mapstochar'], ['\\longrightarrow']], 'loc': (0, 924, 28)},
        '\\longrightarrow': {'definition': [['\\relbar'], ['\\joinrel'], ['\\rightarrow']], 'loc': (0, 921, 28)},
        '\\loop': {'definition': [['\\def'], ['\\body'], '{#1}', ['\\iterate']], 'parameters': [[], [['\\repeat']]], 'loc': (0, 527, 24)},
        '\\lq': {'definition': '`', 'loc': (0, 508, 9)},
        '\\m@g': {'definition': [['\\mag'], ['\\count@'], ' ', ['\\hsize'], '6.5truein', ['\\vsize'], '8.9truein', ['\\dimen'], ['\\footins'], '8truein'], 'loc': (0, 1225, 14)},
        '\\m@ketabbox': {'definition': [['\\begingroup'], ' ', ['\\global'], ['\\setbox'], ['\\tabsyet'], ['\\copy'], ['\\tabs'], ' ', ['\\global'], ['\\setbox'], ['\\tabsdone'], ['\\null'], ' ', ['\\def'], ['\\cr'], '{', ['\\@crtrue'], ['\\crcr'], ['\\egroup'], ['\\egroup'], ' ', ['\\ifus@'], ['\\unvbox'], ['\\z@'], ['\\lastbox'], ['\\fi'], ['\\endgroup'], ' ', ['\\setbox'], ['\\tabs'], ['\\hbox'], '{', ['\\unhbox'], ['\\tabsyet'], ['\\unhbox'], ['\\tabsdone'], '}}', ['\\setbox'], ['\\z@'], ['\\vbox'], ['\\bgroup'], ['\\@crfalse'], ' ', ['\\ialign'], ['\\bgroup'], '&', ['\\t@bbox'], '##', ['\\t@bb@x'], ['\\crcr']], 'loc': (0, 615, 28)},
        '\\m@th': {'definition': [['\\mathsurround'], ['\\z@']], 'loc': (0, 583, 24)},
        '\\magnification': {'definition': [['\\afterassignment'], ['\\m@g'], ['\\count@']], 'loc': (0, 1224, 36)},
        '\\magstep': {'definition': [['\\ifcase'], '#1 ', ['\\@m'], ['\\or'], '1200', ['\\or'], '1440', ['\\or'], '1728', ['\\or'], '2074', ['\\or'], '2488', ['\\fi'], ['\\relax']], 'parameters': 1, 'loc': (0, 391, 23)},
        '\\magstephalf': {'definition': '1095 ', 'loc': (0, 390, 18)},
        '\\makefootline': {'definition': [['\\baselineskip'], '24', ['\\p@'], ['\\lineskiplimit'], ['\\z@'], ['\\line'], '{', ['\\the'], ['\\footline'], '}'], 'loc': (0, 1204, 32)},
        '\\makeheadline': {'definition': [['\\vbox'], 'to', ['\\z@'], '{', ['\\vskip'], '-22.5', ['\\p@'], ' ', ['\\line'], '{', ['\\vbox'], 'to8.5', ['\\p@'], '{}', ['\\the'], ['\\headline'], '}', ['\\vss'], '}', ['\\nointerlineskip']], 'loc': (0, 1202, 25)},
        '\\makeph@nt': {'definition': [['\\setbox'], ['\\z@'], ['\\hbox'], '{#1}', ['\\finph@nt']], 'parameters': 1, 'loc': (0, 1029, 25)},
        '\\makesm@sh': {'definition': [['\\setbox'], ['\\z@'], ['\\hbox'], '{#1}', ['\\finsm@sh']], 'parameters': 1, 'loc': (0, 1038, 25)},
        '\\mapsto': {'definition': [['\\mapstochar'], ['\\rightarrow']], 'loc': (0, 900, 54)},
        '\\mathhexbox': {'definition': [['\\leavevmode'], ' ', ['\\hbox'], '{$', ['\\m@th'], ['\\mathchar'], '"#1#2#3$}'], 'parameters': 3, 'loc': (0, 671, 34)},
        '\\mathpalette': {'definition': [['\\mathchoice'], '{#1', ['\\displaystyle'], '{#2}}{#1', ['\\textstyle'], '{#2}}{#1', ['\\scriptstyle'], '{#2}}{#1', ['\\scriptscriptstyle'], '{#2}}'], 'parameters': 2, 'loc': (0, 1015, 33)},
        '\\mathph@nt': {'definition': [['\\setbox'], ['\\z@'], ['\\hbox'], '{$', ['\\m@th'], '#1{#2}$}', ['\\finph@nt']], 'parameters': 2, 'loc': (0, 1030, 27)},
        '\\mathsm@sh': {'definition': [['\\setbox'], ['\\z@'], ['\\hbox'], '{$', ['\\m@th'], '#1{#2}$}', ['\\finsm@sh']], 'parameters': 2, 'loc': (0, 1039, 27)},
        '\\mathstrut': {'definition': [['\\vphantom'], '('], 'loc': (0, 1034, 25)},
        '\\matrix': {'definition': [['\\null'], ['\\,'], ['\\vcenter'], '{', ['\\normalbaselines'], ['\\m@th'], ' ', ['\\ialign'], '{', ['\\hfil'], '$##$', ['\\hfil'], '&&', ['\\quad'], ['\\hfil'], '$##$', ['\\hfil'], ['\\crcr'], ' ', ['\\mathstrut'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '-', ['\\baselineskip'], '} #1', ['\\crcr'], ['\\mathstrut'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '-', ['\\baselineskip'], '}}}', ['\\,']], 'parameters': 1, 'loc': (0, 1093, 20)},
        '\\max': {'definition': [['\\mathop'], '{', ['\\rm'], 'max}'], 'loc': (0, 1073, 17)},
        '\\medbreak': {'definition': [['\\par'], ['\\ifdim'], ['\\lastskip'], '<', ['\\medskipamount'], ' ', ['\\removelastskip'], ['\\penalty'], '-100', ['\\medskip'], ['\\fi']], 'loc': (0, 570, 19)},
        '\\medskip': {'definition': [['\\vskip'], ['\\medskipamount']], 'loc': (0, 540, 20)},
        '\\midinsert': {'definition': [['\\@midtrue'], ['\\@ins']], 'loc': (0, 1179, 25)},
        '\\min': {'definition': [['\\mathop'], '{', ['\\rm'], 'min}'], 'loc': (0, 1074, 17)},
        '\\mit': {'definition': [['\\fam'], ['\\@ne']], 'loc': (0, 480, 14)},
        '\\models': {'definition': [['\\mathrel'], '|', ['\\joinrel'], '='], 'loc': (0, 919, 21)},
        '\\multispan': {'definition': [['\\omit'], ['\\mscount'], '#1', ['\\relax'], ' ', ['\\loop'], ['\\ifnum'], ['\\mscount'], '>', ['\\@ne'], ['\\sp@n'], ['\\repeat']], 'parameters': 1, 'loc': (0, 594, 24)},
        '\\n@space': {'definition': [['\\nulldelimiterspace'], ['\\z@'], ['\\m@th']], 'loc': (0, 1007, 33)},
        '\\narrower': {'definition': [['\\advance'], ['\\leftskip'], ['\\parindent'], ' ', ['\\advance'], ['\\rightskip'], ['\\parindent']], 'loc': (0, 637, 23)},
        '\\ne': {'definition': [['\\not'], '='], 'macro': 'neq', 'loc': (0, 880, 14)},
        '\\negthinspace': {'definition': [['\\kern'], '-.16667em '], 'loc': (0, 532, 24)},
        '\\neq': {'definition': [['\\not'], '='], 'loc': (0, 880, 14)},
        '\\newbox': {'definition': [['\\alloc@'], '4', ['\\box'], ['\\chardef'], ['\\insc@unt']], 'flags': 'outer', 'loc': (0, 229, 26)},
        '\\newcount': {'definition': [['\\alloc@'], '0', ['\\count'], ['\\countdef'], ['\\insc@unt']], 'flags': 'outer', 'loc': (0, 225, 28)},
        '\\newdimen': {'definition': [['\\alloc@'], '1', ['\\dimen'], ['\\dimendef'], ['\\insc@unt']], 'flags': 'outer', 'loc': (0, 226, 28)},
        '\\newfam': {'definition': [['\\alloc@'], '8', ['\\fam'], ['\\chardef'], ['\\sixt@@n']], 'flags': 'outer', 'loc': (0, 235, 26)},
        '\\newhelp': {'definition': [['\\newtoks'], '#1#1', ['\\expandafter'], '{', ['\\csname'], '#2', ['\\endcsname'], '}'], 'flags': 'outer', 'parameters': 2, 'loc': (0, 231, 32)},
        '\\newif': {'definition': [['\\count@'], ['\\escapechar'], ['\\escapechar'], ['\\m@ne'], ' ', ['\\expandafter'], ['\\expandafter'], ['\\expandafter'], ' ', ['\\def'], ['\\@if'], '#1{true}{', ['\\let'], '#1=', ['\\iftrue'], '}', ['\\expandafter'], ['\\expandafter'], ['\\expandafter'], ' ', ['\\def'], ['\\@if'], '#1{false}{', ['\\let'], '#1=', ['\\iffalse'], '}', ['\\@if'], '#1{false}', ['\\escapechar'], ['\\count@']], 'flags': 'outer', 'parameters': 1, 'loc': (0, 264, 27)},
        '\\newinsert': {'definition': [['\\global'], ['\\advance'], ['\\insc@unt'], 'by', ['\\m@ne'], ' ', ['\\ch@ck'], '0', ['\\insc@unt'], ['\\count'], ' ', ['\\ch@ck'], '1', ['\\insc@unt'], ['\\dimen'], ' ', ['\\ch@ck'], '2', ['\\insc@unt'], ['\\skip'], ' ', ['\\ch@ck'], '4', ['\\insc@unt'], ['\\box'], ' ', ['\\allocationnumber'], '=', ['\\insc@unt'], ' ', ['\\global'], ['\\chardef'], '#1=', ['\\allocationnumber'], ' ', ['\\wlog'], '{', ['\\string'], '#1=', ['\\string'], ['\\insert'], ['\\the'], ['\\allocationnumber'], '}'], 'flags': 'outer', 'parameters': 1, 'loc': (0, 242, 31)},
        '\\newlanguage': {'definition': [['\\alloc@'], '9', ['\\language'], ['\\chardef'], ['\\@cclvi']], 'flags': 'outer', 'loc': (0, 236, 31)},
        '\\newmuskip': {'definition': [['\\alloc@'], '3', ['\\muskip'], ['\\muskipdef'], ['\\@cclvi']], 'flags': 'outer', 'loc': (0, 228, 29)},
        '\\newread': {'definition': [['\\alloc@'], '6', ['\\read'], ['\\chardef'], ['\\sixt@@n']], 'flags': 'outer', 'loc': (0, 233, 27)},
        '\\newskip': {'definition': [['\\alloc@'], '2', ['\\skip'], ['\\skipdef'], ['\\insc@unt']], 'flags': 'outer', 'loc': (0, 227, 27)},
        '\\newtoks': {'definition': [['\\alloc@'], '5', ['\\toks'], ['\\toksdef'], ['\\@cclvi']], 'flags': 'outer', 'loc': (0, 232, 27)},
        '\\newwrite': {'definition': [['\\alloc@'], '7', ['\\write'], ['\\chardef'], ['\\sixt@@n']], 'flags': 'outer', 'loc': (0, 234, 28)},
        '\\nobreak': {'definition': [['\\penalty'], ['\\@M']], 'loc': (0, 559, 23)},
        '\\nointerlineskip': {'definition': [['\\prevdepth'], '-1000', ['\\p@']], 'loc': (0, 543, 32)},
        '\\nonfrenchspacing': {'definition': [['\\sfcode'], '`', ['\\.'], '3000', ['\\sfcode'], '`', ['\\?'], '3000', ['\\sfcode'], '`', ['\\!'], '3000', ['\\sfcode'], '`', ['\\:'], '2000', ['\\sfcode'], '`', ['\\;'], '1500', ['\\sfcode'], '`', ['\\,'], '1250 '], 'loc': (0, 499, 30)},
        '\\nopagenumbers': {'definition': [['\\footline'], '{', ['\\hfil'], '}'], 'loc': (0, 1152, 29)},
        '\\normalbaselines': {'definition': [['\\lineskip'], ['\\normallineskip'], ' ', ['\\baselineskip'], ['\\normalbaselineskip'], ['\\lineskiplimit'], ['\\normallineskiplimit']], 'loc': (0, 502, 31)},
        '\\normalbottom': {'definition': [['\\topskip'], '10', ['\\p@'], ['\\r@ggedbottomfalse']], 'loc': (0, 1150, 28)},
        '\\notin': {'definition': [['\\mathrel'], '{', ['\\mathpalette'], ['\\c@ncel'], ['\\in'], '}'], 'loc': (0, 1045, 20)},
        '\\null': {'definition': [['\\hbox'], '{}'], 'loc': (0, 515, 16)},
        '\\o@lign': {'definition': [['\\lineskiplimit'], ['\\z@'], ['\\oalign']], 'loc': (0, 680, 55)},
        '\\oalign': {'definition': [['\\leavevmode'], ['\\vtop'], '{', ['\\baselineskip'], ['\\z@skip'], ['\\lineskip'], '.25ex', ['\\ialign'], '{##', ['\\crcr'], '#1', ['\\crcr'], '}}'], 'parameters': 1, 'loc': (0, 679, 26)},
        '\\obeylines': {'definition': [['\\catcode'], '`', ['\\^M'], ['\\active'], ['\\let'], [13, '\r'], ['\\par']], 'loc': (0, 522, 27)},
        '\\obeyspaces': {'definition': [['\\catcode'], '`', ['\\ '], ['\\active']], 'loc': (0, 524, 25)},
        '\\offinterlineskip': {'definition': [['\\baselineskip'], '-1000', ['\\p@'], ' ', ['\\lineskip'], ['\\z@'], ['\\lineskiplimit'], ['\\maxdimen']], 'loc': (0, 544, 36)},
        '\\oint': {'definition': [['\\ointop'], ['\\nolimits']], 'loc': (0, 829, 44)},
        '\\oldstyle': {'definition': [['\\fam'], ['\\@ne'], ['\\teni']], 'loc': (0, 480, 38)},
        '\\ooalign': {'definition': [['\\lineskiplimit'], '-', ['\\maxdimen'], ['\\oalign']], 'loc': (0, 681, 28)},
        '\\openup': {'definition': [['\\afterassignment'], ['\\@penup'], ['\\dimen@'], '='], 'loc': (0, 1113, 29)},
        '\\overbrace': {'definition': [['\\mathop'], '{', ['\\vbox'], '{', ['\\m@th'], ['\\ialign'], '{##', ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '3', ['\\p@'], '} ', ['\\downbracefill'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '3', ['\\p@'], ['\\nointerlineskip'], '} $', ['\\hfil'], ['\\displaystyle'], '{#1}', ['\\hfil'], '$', ['\\crcr'], '}}}', ['\\limits']], 'parameters': 1, 'loc': (0, 957, 25)},
        '\\overleftarrow': {'definition': [['\\vbox'], '{', ['\\m@th'], ['\\ialign'], '{##', ['\\crcr'], ' ', ['\\leftarrowfill'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '-', ['\\p@'], ['\\nointerlineskip'], '} $', ['\\hfil'], ['\\displaystyle'], '{#1}', ['\\hfil'], '$', ['\\crcr'], '}}'], 'parameters': 1, 'loc': (0, 954, 27)},
        '\\overrightarrow': {'definition': [['\\vbox'], '{', ['\\m@th'], ['\\ialign'], '{##', ['\\crcr'], ' ', ['\\rightarrowfill'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '-', ['\\p@'], ['\\nointerlineskip'], '} $', ['\\hfil'], ['\\displaystyle'], '{#1}', ['\\hfil'], '$', ['\\crcr'], '}}'], 'parameters': 1, 'loc': (0, 951, 28)},
        '\\pagebody': {'definition': [['\\vbox'], 'to', ['\\vsize'], '{', ['\\boxmaxdepth'], ['\\maxdepth'], ['\\pagecontents'], '}'], 'loc': (0, 1201, 21)},
        '\\pagecontents': {'definition': [['\\ifvoid'], ['\\topins'], ['\\else'], ['\\unvbox'], ['\\topins'], ['\\fi'], ' ', ['\\dimen@'], '=', ['\\dp'], ['\\@cclv'], ['\\unvbox'], ['\\@cclv'], ['\\ifvoid'], ['\\footins'], ['\\else'], ['\\vskip'], ['\\skip'], ['\\footins'], ' ', ['\\footnoterule'], ' ', ['\\unvbox'], ['\\footins'], ['\\fi'], ' ', ['\\ifr@ggedbottom'], ['\\kern'], '-', ['\\dimen@'], ['\\vfil'], ['\\fi']], 'loc': (0, 1208, 26)},
        '\\pageinsert': {'definition': [['\\@midfalse'], ['\\p@getrue'], ['\\@ins']], 'loc': (0, 1180, 27)},
        '\\ph@nt': {'definition': [['\\ifmmode'], ['\\def'], ['\\next'], '{', ['\\mathpalette'], ['\\mathph@nt'], '}', ['\\else'], ['\\let'], ['\\next'], ['\\makeph@nt'], ['\\fi'], ['\\next']], 'loc': (0, 1027, 20)},
        '\\phantom': {'definition': [['\\v@true'], ['\\h@true'], ['\\ph@nt']], 'loc': (0, 1026, 21)},
        '\\plainoutput': {'definition': [['\\shipout'], ['\\vbox'], '{', ['\\makeheadline'], ['\\pagebody'], ['\\makefootline'], '}', ['\\advancepageno'], ' ', ['\\ifnum'], ['\\outputpenalty'], '>-', ['\\@MM'], ['\\else'], ['\\dosupereject'], ['\\fi']], 'loc': (0, 1198, 26)},
        '\\pmatrix': {'definition': [['\\left'], '(', ['\\matrix'], '{#1}', ['\\right'], ')'], 'parameters': 1, 'loc': (0, 1097, 21)},
        '\\pmod': {'definition': [['\\allowbreak'], ['\\mkern'], '18mu({', ['\\rm'], 'mod}', ['\\,'], ['\\,'], '#1)'], 'parameters': 1, 'loc': (0, 1089, 24)},
        '\\pr@@@s': {'definition': [['\\prim@s']], 'parameters': 1, 'loc': (0, 739, 22)},
        '\\pr@@@t': {'definition': ['#2', ['\\egroup']], 'parameters': 2, 'loc': (0, 739, 40)},
        '\\pr@m@s': {'definition': [['\\ifx'], "'", ['\\next'], ['\\let'], ['\\nxt'], ['\\pr@@@s'], ['\\else'], ['\\ifx'], '^', ['\\next'], ['\\let'], ['\\nxt'], ['\\pr@@@t'], ' ', ['\\else'], ['\\let'], ['\\nxt'], ['\\egroup'], ['\\fi'], ['\\fi'], ['\\nxt']], 'loc': (0, 737, 17)},
        '\\prim@s': {'definition': [['\\prime'], ['\\futurelet'], ['\\next'], ['\\pr@m@s']], 'loc': (0, 736, 19)},
        '\\proclaim': {'definition': [['\\medbreak'], ' ', ['\\noindent'], '{', ['\\bf'], '#1.', ['\\enspace'], '}{', ['\\sl'], '#2', ['\\par'], '}', ['\\ifdim'], ['\\lastskip'], '<', ['\\medskipamount'], ['\\removelastskip'], ['\\penalty'], '55', ['\\medskip'], ['\\fi']], 'flags': 'outer', 'parameters': [[], '. ', [['\\par']]], 'loc': (0, 643, 41)},
        '\\qquad': {'definition': [['\\hskip'], '2em', ['\\relax']], 'loc': (0, 537, 18)},
        '\\quad': {'definition': [['\\hskip'], '1em', ['\\relax']], 'loc': (0, 536, 17)},
        '\\r@@t': {'definition': [['\\setbox'], ['\\z@'], ['\\hbox'], '{$', ['\\m@th'], '#1', ['\\sqrt'], '{#2}$}', ['\\dimen@'], ['\\ht'], ['\\z@'], ' ', ['\\advance'], ['\\dimen@'], '-', ['\\dp'], ['\\z@'], ' ', ['\\mkern'], '5mu', ['\\raise'], '.6', ['\\dimen@'], ['\\copy'], ['\\rootbox'], ['\\mkern'], '-10mu', ['\\box'], ['\\z@']], 'parameters': 2, 'loc': (0, 1020, 22)},
        '\\raggedbottom': {'definition': [['\\topskip'], '10', ['\\p@'], 'plus60', ['\\p@'], ['\\r@ggedbottomtrue']], 'loc': (0, 1149, 28)},
        '\\raggedright': {'definition': [['\\rightskip'], ['\\z@'], 'plus2em ', ['\\spaceskip'], '.3333em ', ['\\xspaceskip'], '.5em', ['\\relax']], 'loc': (0, 647, 28)},
        '\\rangle': {'definition': [['\\delimiter'], '"526930B '], 'loc': (0, 982, 23)},
        '\\rbrace': {'definition': [['\\delimiter'], '"5267309 '], 'loc': (0, 984, 23)},
        '\\rbrack': {'definition': ']', 'loc': (0, 509, 28)},
        '\\rceil': {'definition': [['\\delimiter'], '"5265307 '], 'loc': (0, 986, 22)},
        '\\relbar': {'definition': [['\\mathrel'], '{', ['\\smash'], '-}'], 'loc': (0, 914, 21)},
        '\\removelastskip': {'definition': [['\\ifdim'], ['\\lastskip'], '=', ['\\z@'], ['\\else'], ['\\vskip'], '-', ['\\lastskip'], ['\\fi']], 'loc': (0, 567, 27)},
        '\\rfloor': {'definition': [['\\delimiter'], '"5263305 '], 'loc': (0, 988, 23)},
        '\\rgroup': {'definition': [['\\delimiter'], '"562933B '], 'loc': (0, 969, 23)},
        '\\rightarrowfill': {'definition': ['$', ['\\m@th'], ['\\smash'], '-', ['\\mkern'], '-7mu', ['\\cleaders'], ['\\hbox'], '{$', ['\\mkern'], '-2mu', ['\\smash'], '-', ['\\mkern'], '-2mu$}', ['\\hfill'], ' ', ['\\mkern'], '-7mu', ['\\mathord'], ['\\rightarrow'], '$'], 'loc': (0, 709, 21)},
        '\\rightleftharpoons': {'definition': [['\\mathrel'], '{', ['\\mathpalette'], ['\\rlh@'], '{}}'], 'loc': (0, 1047, 32)},
        '\\rightline': {'definition': [['\\line'], '{', ['\\hss'], '#1}'], 'parameters': 1, 'loc': (0, 577, 23)},
        '\\rlap': {'definition': [['\\hbox'], 'to', ['\\z@'], '{#1', ['\\hss'], '}'], 'parameters': 1, 'loc': (0, 580, 19)},
        '\\rlh@': {'definition': [['\\vcenter'], '{', ['\\m@th'], ['\\hbox'], '{', ['\\ooalign'], '{', ['\\raise'], '2pt ', ['\\hbox'], '{$#1', ['\\rightharpoonup'], '$}', ['\\crcr'], ' $#1', ['\\leftharpoondown'], '$}}}'], 'parameters': 1, 'loc': (0, 1048, 21)},
        '\\rm': {'definition': [['\\fam'], ['\\z@'], ['\\tenrm']], 'loc': (0, 478, 13)},
        '\\rmoustache': {'definition': [['\\delimiter'], '"537B341 '], 'loc': (0, 967, 27)},
        '\\root': {'definition': [['\\setbox'], ['\\rootbox'], ' ', ['\\hbox'], '{$', ['\\m@th'], ['\\scriptscriptstyle'], '{#1}$}', ['\\mathpalette'], ['\\r@@t']], 'parameters': [[], [['\\of']]], 'loc': (0, 1018, 23)},
        '\\rq': {'definition': "'", 'loc': (0, 508, 20)},
        '\\s@tcols': {'definition': [['\\count@'], '#1', ['\\dimen@'], ['\\hsize'], ' ', ['\\loop'], ['\\ifnum'], ['\\count@'], '>', ['\\z@'], ['\\@nother'], ['\\repeat']], 'parameters': [[], [['\\columns']]], 'loc': (0, 609, 31)},
        '\\s@tt@b': {'definition': [['\\let'], ['\\nxt'], ['\\relax'], ['\\us@false'], ['\\m@ketabbox']], 'loc': (0, 606, 17)},
        '\\sec': {'definition': [['\\mathop'], '{', ['\\rm'], 'sec}', ['\\nolimits']], 'loc': (0, 1071, 17)},
        '\\sett@b': {'definition': [['\\ifx'], ['\\next'], ['\\+'], ['\\def'], ['\\nxt'], '{', ['\\afterassignment'], ['\\s@tt@b'], ['\\let'], ['\\nxt'], '}', ['\\else'], ['\\let'], ['\\nxt'], ['\\s@tcols'], ['\\fi'], ['\\let'], ['\\next'], ['\\relax'], ['\\nxt']], 'loc': (0, 604, 17)},
        '\\settabs': {'definition': [['\\setbox'], ['\\tabs'], ['\\null'], ['\\futurelet'], ['\\next'], ['\\sett@b']], 'loc': (0, 602, 21)},
        '\\sh@ft': {'definition': [['\\dimen@'], '#1', ['\\kern'], ['\\expandafter'], ['\\getf@ctor'], ['\\the'], ['\\fontdimen'], '1', ['\\font'], ' ', ['\\dimen@']], 'parameters': 1, 'loc': (0, 683, 21)},
        '\\showhyphens': {'definition': [['\\setbox'], '0', ['\\vbox'], '{', ['\\parfillskip'], ['\\z@skip'], ['\\hsize'], ['\\maxdimen'], ['\\tenrm'], ' ', ['\\pretolerance'], ['\\m@ne'], ['\\tolerance'], ['\\m@ne'], ['\\hbadness'], '0', ['\\showboxdepth'], '0', ['\\ '], '#1}'], 'parameters': 1, 'loc': (0, 1234, 27)},
        '\\sin': {'definition': [['\\mathop'], '{', ['\\rm'], 'sin}', ['\\nolimits']], 'loc': (0, 1060, 17)},
        '\\sinh': {'definition': [['\\mathop'], '{', ['\\rm'], 'sinh}', ['\\nolimits']], 'loc': (0, 1062, 18)},
        '\\skew': {'definition': ['{', ['\\muskip'], ['\\z@'], '#1mu', ['\\divide'], ['\\muskip'], ['\\z@'], ['\\tw@'], ['\\mkern'], ['\\muskip'], ['\\z@'], ' #2{', ['\\mkern'], '-', ['\\muskip'], ['\\z@'], '{#3}', ['\\mkern'], ['\\muskip'], ['\\z@'], '}', ['\\mkern'], '-', ['\\muskip'], ['\\z@'], '}{}'], 'parameters': 3, 'loc': (0, 963, 17)},
        '\\sl': {'definition': [['\\fam'], ['\\slfam'], ['\\tensl']], 'loc': (0, 486, 27)},
        '\\slash': {'definition': ['/', ['\\penalty'], ['\\exhyphenpenalty']], 'loc': (0, 556, 12)},
        '\\smallbreak': {'definition': [['\\par'], ['\\ifdim'], ['\\lastskip'], '<', ['\\smallskipamount'], ' ', ['\\removelastskip'], ['\\penalty'], '-50', ['\\smallskip'], ['\\fi']], 'loc': (0, 568, 21)},
        '\\smallskip': {'definition': [['\\vskip'], ['\\smallskipamount']], 'loc': (0, 539, 22)},
        '\\smash': {'definition': [['\\relax'], ['\\ifmmode'], ['\\def'], ['\\next'], '{', ['\\mathpalette'], ['\\mathsm@sh'], '}', ['\\else'], ['\\let'], ['\\next'], ['\\makesm@sh'], ' ', ['\\fi'], ['\\next']], 'loc': (0, 1035, 19)},
        '\\sp@n': {'definition': [['\\span'], ['\\omit'], ['\\advance'], ['\\mscount'], ['\\m@ne']], 'loc': (0, 596, 16)},
        '\\space': {'definition': ' ', 'loc': (0, 513, 12)},
        '\\sqrt': {'definition': [['\\radical'], '"270370 '], 'loc': (0, 1013, 19)},
        '\\strut': {'definition': [['\\relax'], ['\\ifmmode'], ['\\copy'], ['\\strutbox'], ['\\else'], ['\\unhcopy'], ['\\strutbox'], ['\\fi']], 'loc': (0, 589, 18)},
        '\\sup': {'definition': [['\\mathop'], '{', ['\\rm'], 'sup}'], 'loc': (0, 1075, 17)},
        '\\supereject': {'definition': [['\\par'], ['\\penalty'], '-', ['\\@MM']], 'loc': (0, 565, 21)},
        '\\surd': {'definition': ['{', ['\\mathchar'], '"1270}'], 'loc': (0, 798, 11)},
        '\\t': {'definition': ['{', ['\\edef'], ['\\next'], '{', ['\\the'], ['\\font'], '}', ['\\the'], ['\\textfont'], '1', ['\\accent'], '"7F', ['\\next'], '#1}'], 'parameters': 1, 'loc': (0, 705, 10)},
        '\\t@bb@x': {'definition': [['\\if@cr'], ['\\egroup'], ['\\else'], ['\\hss'], ['\\egroup'], ['\\global'], ['\\setbox'], ['\\tabsyet'], ['\\hbox'], '{', ['\\unhbox'], ['\\tabsyet'], ' ', ['\\global'], ['\\setbox'], ['\\@ne'], ['\\lastbox'], '}', ['\\ifvoid'], ['\\@ne'], ['\\global'], ['\\setbox'], ['\\@ne'], ['\\hbox'], 'to', ['\\wd'], ['\\z@'], '{}', ['\\else'], ['\\setbox'], ['\\z@'], ['\\hbox'], 'to', ['\\wd'], ['\\@ne'], '{', ['\\unhbox'], ['\\z@'], '}', ['\\fi'], ' ', ['\\global'], ['\\setbox'], ['\\tabsdone'], ['\\hbox'], '{', ['\\box'], ['\\@ne'], ['\\unhbox'], ['\\tabsdone'], '}', ['\\fi'], ' ', ['\\box'], ['\\z@']], 'loc': (0, 625, 19)},
        '\\t@bbox': {'definition': [['\\setbox'], ['\\z@'], ['\\hbox'], ['\\bgroup']], 'loc': (0, 624, 20)},
        '\\tabalign': {'definition': [['\\us@true'], ['\\m@ketabbox']], 'loc': (0, 607, 23)},
        '\\tan': {'definition': [['\\mathop'], '{', ['\\rm'], 'tan}', ['\\nolimits']], 'loc': (0, 1066, 17)},
        '\\tanh': {'definition': [['\\mathop'], '{', ['\\rm'], 'tanh}', ['\\nolimits']], 'loc': (0, 1068, 18)},
        '\\textindent': {'definition': [['\\indent'], ['\\llap'], '{#1', ['\\enspace'], '}', ['\\ignorespaces']], 'parameters': 1, 'loc': (0, 634, 26)},
        '\\thinspace': {'definition': [['\\kern'], '.16667em '], 'loc': (0, 531, 22)},
        '\\tilde': {'definition': [['\\mathaccent'], '"707E '], 'loc': (0, 942, 23)},
        '\\topglue': {'definition': [['\\nointerlineskip'], ['\\vglue'], '-', ['\\topskip'], ['\\vglue']], 'loc': (0, 547, 30)},
        '\\topinsert': {'definition': [['\\@midfalse'], ['\\p@gefalse'], ['\\@ins']], 'loc': (0, 1178, 26)},
        '\\tracingall': {'definition': [['\\tracingonline'], ['\\@ne'], ['\\loggingall']], 'loc': (0, 1232, 31)},
        '\\tt': {'definition': [['\\fam'], ['\\ttfam'], ['\\tentt']], 'loc': (0, 491, 27)},
        '\\ttraggedright': {'definition': [['\\tt'], ['\\rightskip'], ['\\z@'], 'plus2em', ['\\relax']], 'loc': (0, 648, 23)},
        '\\u': {'definition': ['{', ['\\accent'], '21 #1}'], 'parameters': 1, 'loc': (0, 698, 10)},
        '\\underbar': {'definition': ['$', ['\\setbox'], ['\\z@'], ['\\hbox'], '{#1}', ['\\dp'], ['\\z@'], ['\\z@'], ' ', ['\\m@th'], ['\\underline'], '{', ['\\box'], ['\\z@'], '}$'], 'parameters': 1, 'loc': (0, 584, 17)},
        '\\underbrace': {'definition': [['\\mathop'], '{', ['\\vtop'], '{', ['\\m@th'], ['\\ialign'], '{##', ['\\crcr'], ' $', ['\\hfil'], ['\\displaystyle'], '{#1}', ['\\hfil'], '$', ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '3', ['\\p@'], ['\\nointerlineskip'], '} ', ['\\upbracefill'], ['\\crcr'], ['\\noalign'], '{', ['\\kern'], '3', ['\\p@'], '}}}}', ['\\limits']], 'parameters': 1, 'loc': (0, 960, 26)},
        '\\uparrow': {'definition': [['\\delimiter'], '"3222378 '], 'loc': (0, 975, 24)},
        '\\upbracefill': {'definition': ['$', ['\\m@th'], ['\\setbox'], ['\\z@'], ['\\hbox'], '{$', ['\\braceld'], '$}', ['\\bracelu'], ['\\leaders'], ['\\vrule'], 'height', ['\\ht'], ['\\z@'], 'depth', ['\\z@'], ['\\hfill'], ['\\bracerd'], ' ', ['\\braceld'], ['\\leaders'], ['\\vrule'], 'height', ['\\ht'], ['\\z@'], 'depth', ['\\z@'], ['\\hfill'], ['\\braceru'], '$'], 'loc': (0, 720, 18)},
        '\\updownarrow': {'definition': [['\\delimiter'], '"326C33F '], 'loc': (0, 977, 28)},
        '\\v': {'definition': ['{', ['\\accent'], '20 #1}'], 'parameters': 1, 'loc': (0, 697, 10)},
        '\\vdots': {'definition': [['\\vbox'], '{', ['\\baselineskip'], '4', ['\\p@'], ['\\lineskiplimit'], ['\\z@'], ' ', ['\\kern'], '6', ['\\p@'], ['\\hbox'], '{.}', ['\\hbox'], '{.}', ['\\hbox'], '{.}}'], 'loc': (0, 934, 17)},
        '\\vec': {'definition': [['\\mathaccent'], '"017E '], 'loc': (0, 947, 21)},
        '\\vert': {'definition': [['\\delimiter'], '"26A30C '], 'loc': (0, 974, 21)},
        '\\vfootnote': {'definition': [['\\insert'], ['\\footins'], ['\\bgroup'], ' ', ['\\interlinepenalty'], ['\\interfootnotelinepenalty'], ' ', ['\\splittopskip'], ['\\ht'], ['\\strutbox'], ['\\splitmaxdepth'], ['\\dp'], ['\\strutbox'], ['\\floatingpenalty'], ['\\@MM'], ' ', ['\\leftskip'], ['\\z@skip'], ['\\rightskip'], ['\\z@skip'], ['\\spaceskip'], ['\\z@skip'], ['\\xspaceskip'], ['\\z@skip'], ' ', ['\\textindent'], '{#1}', ['\\footstrut'], ['\\futurelet'], ['\\next'], ['\\fo@t']], 'parameters': 1, 'loc': (0, 1160, 25)},
        '\\vgl@': {'definition': [['\\par'], ['\\dimen@'], ['\\prevdepth'], ['\\hrule'], 'height', ['\\z@'], ' ', ['\\nobreak'], ['\\vskip'], ['\\skip@'], ['\\prevdepth'], ['\\dimen@']], 'loc': (0, 549, 16)},
        '\\vglue': {'definition': [['\\afterassignment'], ['\\vgl@'], ['\\skip@'], '='], 'loc': (0, 548, 28)},
        '\\vphantom': {'definition': [['\\v@true'], ['\\h@false'], ['\\ph@nt']], 'loc': (0, 1024, 22)},
        '\\widehat': {'definition': [['\\mathaccent'], '"0362 '], 'loc': (0, 950, 25)},
        '\\widetilde': {'definition': [['\\mathaccent'], '"0365 '], 'loc': (0, 949, 27)},
        '\\wlog': {'definition': [['\\immediate'], ['\\write'], ['\\m@ne']], 'loc': (0, 207, 21)},
        '\\{': {'definition': [['\\delimiter'], '"4266308 '], 'macro': 'lbrace', 'loc': (0, 985, 23)},
        '\\|': {'definition': [['\\delimiter'], '"26B30D '], 'macro': 'Vert', 'loc': (0, 973, 21)},
        '\\}': {'definition': [['\\delimiter'], '"5267309 '], 'macro': 'rbrace', 'loc': (0, 984, 23)},
        '\\~': {'definition': ['{', ['\\accent'], '"7E #1}'], 'parameters': 1, 'loc': (0, 703, 10)},
        '~': {'definition': [['\\penalty'], ['\\@M'], ['\\ ']], 'loc': (0, 555, 15)},
        }

    LOCATION_FILENAMES = {
        0: 'plain.tex',
        }

    OTHER = {
        '\r': {'control': 'par'},       '\\#': {'char': 35},
        '\\$': {'char': 36},    '\\%': {'char': 37},    '\\&': {'char': 38},
        '\\@M': {'char': 10000},        '\\@MM': {'char': 20000},
        '\\@cclv': {'char': 255},       '\\@cclvi': {'char': 256},
        '\\@m': {'char': 1000}, '\\@ne': {'char': 1},   '\\AE': {'char': 29},
        '\\Delta': {'char': 28673},     '\\Gamma': {'char': 28672},
        '\\Im': {'char': 573},  '\\Lambda': {'char': 28675},
        '\\Leftarrow': {'char': 12840}, '\\Leftrightarrow': {'char': 12844},
        '\\O': {'char': 31},    '\\OE': {'char': 30},
        '\\Omega': {'char': 28682},     '\\Phi': {'char': 28680},
        '\\Pi': {'char': 28677},        '\\Psi': {'char': 28681},
        '\\Re': {'char': 572},  '\\Rightarrow': {'char': 12841},
        '\\Sigma': {'char': 28678},     '\\Theta': {'char': 28674},
        '\\Upsilon': {'char': 28679},   '\\Xi': {'char': 28676},
        '\\abovedisplayshortskip': {'control': 'abovedisplayshortskip', 'value': [0, 196608, 0]},
        '\\abovedisplayskip': {'control': 'abovedisplayskip', 'value': [786432, 196608, 0, 589824, 0]},
        '\\active': {'char': 13},
        '\\adjdemerits': {'control': 'adjdemerits', 'value': 10000},
        '\\ae': {'char': 26},   '\\aleph': {'char': 576},
        '\\allocationnumber': {'register': '\\count21'},
        '\\alpha': {'char': 267},       '\\amalg': {'char': 8817},
        '\\approx': {'char': 12825},    '\\ast': {'char': 8707},
        '\\asymp': {'char': 12816},
        '\\baselineskip': {'control': 'baselineskip', 'value': [786432]},
        '\\belowdisplayshortskip': {'control': 'belowdisplayshortskip', 'value': [458752, 196608, 0, 262144, 0]},
        '\\belowdisplayskip': {'control': 'belowdisplayskip', 'value': [786432, 196608, 0, 589824, 0]},
        '\\beta': {'char': 268},        '\\bffam': {'char': 6},
        '\\bgroup': {'control': 'redefined_by_let'},
        '\\bigcap': {'char': 4948},     '\\bigcirc': {'char': 8717},
        '\\bigcup': {'char': 4947},     '\\bigodot': {'char': 4938},
        '\\bigoplus': {'char': 4940},   '\\bigotimes': {'char': 4942},
        '\\bigskipamount': {'register': '\\skip15'},
        '\\bigsqcup': {'char': 4934},   '\\bigtriangledown': {'char': 8757},
        '\\bigtriangleup': {'char': 8756},      '\\biguplus': {'char': 4949},
        '\\bigvee': {'char': 4951},     '\\bigwedge': {'char': 4950},
        '\\binoppenalty': {'control': 'binoppenalty', 'value': 700},
        '\\bot': {'char': 575},
        '\\box0': {'font': 'cmex10', 'hbox': [{'breakpoint': []}, 'B']},
        '\\box11': {'hbox': [{'breakpoint': []}, {'d': 229376, 'h': 557056, 'rule': []}]},
        '\\boxmaxdepth': {'control': 'boxmaxdepth', 'value': 1073741823},
        '\\braceld': {'char': 890},     '\\bracelu': {'char': 892},
        '\\bracerd': {'char': 891},     '\\braceru': {'char': 893},
        '\\brokenpenalty': {'control': 'brokenpenalty', 'value': 100},
        '\\bullet': {'char': 8719},     '\\cap': {'char': 8796},
        '\\catcode1': 8,        '\\catcode11': 7,       '\\catcode12': 13,
        '\\catcode9': 10,       '\\cdot': {'char': 8705},
        '\\cdotp': {'char': 25089},
        '\\centering': {'register': '\\skip11'},
        '\\chi': {'char': 287}, '\\circ': {'char': 8718},
        '\\clubpenalty': {'control': 'clubpenalty', 'value': 150},
        '\\clubsuit': {'char': 636},    '\\colon': {'char': 24634},
        '\\coprod': {'char': 4960},
        '\\copy0': {'font': 'cmex10', 'hbox': [{'breakpoint': []}, 'B']},
        '\\copy11': {'hbox': [{'breakpoint': []}, {'d': 229376, 'h': 557056, 'rule': []}]},
        '\\count0': 1,  '\\count10': 25,        '\\count11': 15,
        '\\count12': 17,        '\\count13': 9, '\\count14': 15,
        '\\count15': 11,        '\\count16': -1,        '\\count17': -1,
        '\\count18': 7, '\\count19': 0, '\\count20': 253,
        '\\count21': 253,       '\\count22': -1,        '\\count23': 100,
        '\\count24': 100,       '\\count253': 1000,     '\\count254': 1000,
        '\\count255': 92,       '\\count@': {'register': '\\count255'},
        '\\cup': {'char': 8795},        '\\dagger': {'char': 8825},
        '\\dashv': {'char': 12897},     '\\ddagger': {'char': 8826},
        '\\defaulthyphenchar': {'control': 'defaulthyphenchar', 'value': 45},
        '\\defaultskewchar': {'control': 'defaultskewchar', 'value': -1},
        '\\delcode124': 2532108,        '\\delcode40': 164608,
        '\\delcode41': 168705,  '\\delcode47': 193294,
        '\\delcode60': 2523914, '\\delcode62': 2528011, '\\delcode91': 373506,
        '\\delcode92': 2548495, '\\delcode93': 381699,
        '\\delimiterfactor': {'control': 'delimiterfactor', 'value': 901},
        '\\delimitershortfall': {'control': 'delimitershortfall', 'value': 327680},
        '\\delta': {'char': 270},       '\\diamond': {'char': 8709},
        '\\diamondsuit': {'char': 637}, '\\dimen10': 1073741823,
        '\\dimen11': 65536,     '\\dimen12': 0, '\\dimen13': 0,
        '\\dimen14': 196608,    '\\dimen15': 573441,
        '\\dimen253': 1073741823,       '\\dimen254': 37890288,
        '\\dimen@': {'register': '\\dimen0'},
        '\\dimen@i': {'register': '\\dimen1'},
        '\\dimen@ii': {'register': '\\dimen2'},
        '\\displaywidowpenalty': {'control': 'displaywidowpenalty', 'value': 50},
        '\\div': {'char': 8708},
        '\\doublehyphendemerits': {'control': 'doublehyphendemerits', 'value': 10000},
        '\\egroup': {'control': 'redefined_by_let'},
        '\\ell': {'char': 352}, '\\emptyset': {'char': 571},
        '\\endgraf': {'control': 'par'},
        '\\endline': {'control': 'cr'}, '\\epsilon': {'char': 271},
        '\\equiv': {'char': 12817},
        '\\errorcontextlines': {'control': 'errorcontextlines', 'value': 5},
        '\\eta': {'char': 273},
        '\\exhyphenpenalty': {'control': 'exhyphenpenalty', 'value': 50},
        '\\exists': {'char': 569},
        '\\finalhyphendemerits': {'control': 'finalhyphendemerits', 'value': 5000},
        '\\fivebf': {'font': 'cmbx5', 'setter': 'fivebf', 'source': 'cmbx5'},
        '\\fivei': {'font': 'cmmi5', 'setter': 'fivei', 'skewchar': 127, 'source': 'cmmi5'},
        '\\fiverm': {'font': 'cmr5', 'setter': 'fiverm', 'source': 'cmr5'},
        '\\fivesy': {'font': 'cmsy5', 'setter': 'fivesy', 'skewchar': 48, 'source': 'cmsy5'},
        '\\flat': {'char': 347},        '\\footins': {'char': 254},
        '\\footline': {'register': '\\toks11'}, '\\forall': {'char': 568},
        '\\frown': {'char': 12639},     '\\gamma': {'char': 269},
        '\\ge': {'char': 12821},        '\\geq': {'char': 12821},
        '\\gets': {'char': 12832},      '\\gg': {'char': 12829},
        '\\hbadness': {'control': 'hbadness', 'value': 1000},
        '\\headline': {'register': '\\toks10'}, '\\heartsuit': {'char': 638},
        '\\hfuzz': {'control': 'hfuzz', 'value': 6554},
        '\\hideskip': {'register': '\\skip10'},
        '\\hsize': {'control': 'hsize', 'value': 30785859},
        '\\hyphenpenalty': {'control': 'hyphenpenalty', 'value': 50},
        '\\i': {'char': 16},    '\\if@cr': {'control': 'iffalse'},
        '\\if@mid': {'control': 'iffalse'},
        '\\ifdt@p': {'control': 'iffalse'},
        '\\ifh@': {'control': 'iffalse'},
        '\\ifp@ge': {'control': 'iffalse'},
        '\\ifr@ggedbottom': {'control': 'iffalse'},
        '\\ifus@': {'control': 'iffalse'},
        '\\ifv@': {'control': 'iffalse'},       '\\imath': {'char': 379},
        '\\in': {'char': 12850},        '\\infty': {'char': 561},
        '\\insc@unt': {'register': '\\count20'},
        '\\interdisplaylinepenalty': {'register': '\\count23'},
        '\\interfootnotelinepenalty': {'register': '\\count24'},
        '\\intop': {'char': 4946},      '\\iota': {'char': 275},
        '\\itfam': {'char': 4}, '\\j': {'char': 17},
        '\\jmath': {'char': 380},       '\\jot': {'register': '\\dimen14'},
        '\\kappa': {'char': 276},       '\\lambda': {'char': 277},
        '\\land': {'char': 8798},       '\\ldotp': {'char': 24890},
        '\\le': {'char': 12820},        '\\leftarrow': {'char': 12832},
        '\\leftharpoondown': {'char': 12585},
        '\\leftharpoonup': {'char': 12584},
        '\\lefthyphenmin': {'control': 'lefthyphenmin', 'value': 2},
        '\\leftrightarrow': {'char': 12836},    '\\leq': {'char': 12820},
        '\\lhook': {'char': 12588},
        '\\linepenalty': {'control': 'linepenalty', 'value': 10},
        '\\lineskip': {'control': 'lineskip', 'value': [65536]},
        '\\ll': {'char': 12828},        '\\lnot': {'char': 570},
        '\\lor': {'char': 8799},        '\\m@ne': {'register': '\\count22'},
        '\\mapstochar': {'char': 12855},        '\\mathcode0': 8705,
        '\\mathcode1': 12835,   '\\mathcode10': 270,    '\\mathcode11': 12834,
        '\\mathcode12': 8710,   '\\mathcode123': 16998, '\\mathcode124': 618,
        '\\mathcode125': 21095, '\\mathcode127': 4723,  '\\mathcode13': 8712,
        '\\mathcode14': 561,    '\\mathcode15': 320,    '\\mathcode16': 12826,
        '\\mathcode17': 12827,  '\\mathcode18': 8796,   '\\mathcode19': 8795,
        '\\mathcode2': 267,     '\\mathcode20': 568,    '\\mathcode21': 569,
        '\\mathcode22': 8714,   '\\mathcode23': 12836,  '\\mathcode24': 12832,
        '\\mathcode25': 12833,  '\\mathcode26': 32768,  '\\mathcode27': 8709,
        '\\mathcode28': 12820,  '\\mathcode29': 12821,  '\\mathcode3': 268,
        '\\mathcode30': 12817,  '\\mathcode31': 8799,   '\\mathcode32': 32768,
        '\\mathcode33': 20513,  '\\mathcode39': 32768,  '\\mathcode4': 8798,
        '\\mathcode40': 16424,  '\\mathcode41': 20521,  '\\mathcode42': 8707,
        '\\mathcode43': 8235,   '\\mathcode44': 24891,  '\\mathcode45': 8704,
        '\\mathcode46': 314,    '\\mathcode47': 317,    '\\mathcode5': 570,
        '\\mathcode58': 12346,  '\\mathcode59': 24635,  '\\mathcode6': 12850,
        '\\mathcode60': 12604,  '\\mathcode61': 12349,  '\\mathcode62': 12606,
        '\\mathcode63': 20543,  '\\mathcode7': 281,     '\\mathcode8': 277,
        '\\mathcode9': 269,     '\\mathcode91': 16475,  '\\mathcode92': 622,
        '\\mathcode93': 20573,  '\\mathcode95': 32768,
        '\\maxdepth': {'control': 'maxdepth', 'value': 262144},
        '\\maxdimen': {'register': '\\dimen10'},
        '\\medmuskip': {'control': 'medmuskip', 'value': [262144, 131072, 0, 262144, 0]},
        '\\medskipamount': {'register': '\\skip14'},
        '\\mid': {'char': 12906},       '\\mp': {'char': 8711},
        '\\mscount': {'register': '\\count25'}, '\\mu': {'char': 278},
        '\\nabla': {'char': 626},       '\\natural': {'char': 348},
        '\\nearrow': {'char': 12837},   '\\neg': {'char': 570},
        '\\newlinechar': {'control': 'newlinechar', 'value': -1},
        '\\ni': {'char': 12851},
        '\\normalbaselineskip': {'register': '\\skip16'},
        '\\normallineskip': {'register': '\\skip17'},
        '\\normallineskiplimit': {'register': '\\dimen13'},
        '\\not': {'char': 12854},       '\\nu': {'char': 279},
        '\\nulldelimiterspace': {'control': 'nulldelimiterspace', 'value': 78643},
        '\\nwarrow': {'char': 12845},   '\\o': {'char': 28},
        '\\odot': {'char': 8716},       '\\oe': {'char': 27},
        '\\ointop': {'char': 4936},     '\\omega': {'char': 289},
        '\\ominus': {'char': 8713},     '\\oplus': {'char': 8712},
        '\\oslash': {'char': 8715},     '\\otimes': {'char': 8714},
        '\\output': {'control': 'output', 'value': [['\\plainoutput']]},
        '\\overfullrule': {'control': 'overfullrule', 'value': 327680},
        '\\owns': {'char': 12851},      '\\p@': {'register': '\\dimen11'},
        '\\p@renwd': {'register': '\\dimen15'},
        '\\pageno': {'register': '\\count0'},   '\\parallel': {'char': 12907},
        '\\parskip': {'control': 'parskip', 'value': [0, 65536, 0]},
        '\\partial': {'char': 320},     '\\perp': {'char': 12863},
        '\\phi': {'char': 286}, '\\pi': {'char': 281},
        '\\pm': {'char': 8710}, '\\prec': {'char': 12830},
        '\\preceq': {'char': 12822},
        '\\predisplaypenalty': {'control': 'predisplaypenalty', 'value': 10000},
        '\\pretolerance': {'control': 'pretolerance', 'value': 100},
        '\\prevdepth': {'control': 'prevdepth', 'value': 0},
        '\\prime': {'char': 560},       '\\prod': {'char': 4945},
        '\\propto': {'char': 12847},    '\\psi': {'char': 288},
        '\\relpenalty': {'control': 'relpenalty', 'value': 500},
        '\\repeat': {'control': 'fi'},  '\\rho': {'char': 282},
        '\\rhook': {'char': 12589},     '\\rightarrow': {'char': 12833},
        '\\rightharpoondown': {'char': 12587},
        '\\rightharpoonup': {'char': 12586},
        '\\righthyphenmin': {'control': 'righthyphenmin', 'value': 3},
        '\\rootbox': {'char': 15},
        '\\sb': {'control': 'redefined_by_let'},
        '\\scriptfont0': {'font': 'cmr7', 'source': 'cmr7'},
        '\\scriptfont1': {'font': 'cmmi7', 'skewchar': 127, 'source': 'cmmi7'},
        '\\scriptfont2': {'font': 'cmsy7', 'skewchar': 48, 'source': 'cmsy7'},
        '\\scriptfont3': {'font': 'cmex10', 'source': 'cmex10', 'used': 1},
        '\\scriptfont6': {'font': 'cmbx7', 'source': 'cmbx7'},
        '\\scriptscriptfont0': {'font': 'cmr5', 'source': 'cmr5'},
        '\\scriptscriptfont1': {'font': 'cmmi5', 'skewchar': 127, 'source': 'cmmi5'},
        '\\scriptscriptfont2': {'font': 'cmsy5', 'skewchar': 48, 'source': 'cmsy5'},
        '\\scriptscriptfont3': {'font': 'cmex10', 'source': 'cmex10', 'used': 1},
        '\\scriptscriptfont6': {'font': 'cmbx5', 'source': 'cmbx5'},
        '\\scriptspace': {'control': 'scriptspace', 'value': 32768},
        '\\searrow': {'char': 12838},   '\\setminus': {'char': 8814},
        '\\sevenbf': {'font': 'cmbx7', 'setter': 'sevenbf', 'source': 'cmbx7'},
        '\\seveni': {'font': 'cmmi7', 'setter': 'seveni', 'skewchar': 127, 'source': 'cmmi7'},
        '\\sevenrm': {'font': 'cmr7', 'setter': 'sevenrm', 'source': 'cmr7'},
        '\\sevensy': {'font': 'cmsy7', 'setter': 'sevensy', 'skewchar': 48, 'source': 'cmsy7'},
        '\\sfcode33': 3000,     '\\sfcode39': 0,        '\\sfcode41': 0,
        '\\sfcode44': 1250,     '\\sfcode46': 3000,     '\\sfcode58': 2000,
        '\\sfcode59': 1500,     '\\sfcode63': 3000,     '\\sfcode93': 0,
        '\\sharp': {'char': 349},
        '\\showboxbreadth': {'control': 'showboxbreadth', 'value': 5},
        '\\showboxdepth': {'control': 'showboxdepth', 'value': 3},
        '\\sigma': {'char': 283},       '\\sim': {'char': 12824},
        '\\simeq': {'char': 12839},     '\\sixt@@n': {'char': 16},
        '\\skip10': [-65536000, 65536, 2],
        '\\skip11': [0, 65536000, 0, 65536000, 0],      '\\skip12': [0],
        '\\skip13': [196608, 65536, 0, 65536, 0],
        '\\skip14': [393216, 131072, 0, 131072, 0],
        '\\skip15': [786432, 262144, 0, 262144, 0],     '\\skip16': [786432],
        '\\skip17': [65536],    '\\skip253': [0],
        '\\skip254': [786432, 262144, 0, 262144, 0],
        '\\skip@': {'register': '\\skip0'},     '\\slfam': {'char': 5},
        '\\smallint': {'char': 4723},
        '\\smallskipamount': {'register': '\\skip13'},
        '\\smile': {'char': 12638},
        '\\sp': {'control': 'redefined_by_let'},
        '\\spadesuit': {'char': 639},
        '\\splitmaxdepth': {'control': 'splitmaxdepth', 'value': 1073741823},
        '\\splittopskip': {'control': 'splittopskip', 'value': [655360]},
        '\\sqcap': {'char': 8821},      '\\sqcup': {'char': 8820},
        '\\sqsubseteq': {'char': 12918},
        '\\sqsupseteq': {'char': 12919},        '\\ss': {'char': 25},
        '\\star': {'char': 8511},       '\\strutbox': {'char': 11},
        '\\subset': {'char': 12826},    '\\subseteq': {'char': 12818},
        '\\succ': {'char': 12831},      '\\succeq': {'char': 12823},
        '\\sum': {'char': 4944},        '\\supset': {'char': 12827},
        '\\supseteq': {'char': 12819},  '\\swarrow': {'char': 12846},
        '\\tabs': {'char': 12}, '\\tabsdone': {'char': 14},
        '\\tabsyet': {'char': 13},      '\\tau': {'char': 284},
        '\\tenbf': {'font': 'cmbx10', 'setter': 'tenbf', 'source': 'cmbx10'},
        '\\tenex': {'font': 'cmex10', 'setter': 'tenex', 'source': 'cmex10', 'used': 1},
        '\\teni': {'font': 'cmmi10', 'setter': 'teni', 'skewchar': 127, 'source': 'cmmi10'},
        '\\tenit': {'font': 'cmti10', 'setter': 'tenit', 'source': 'cmti10'},
        '\\tenrm': {'font': 'cmr10', 'setter': 'tenrm', 'source': 'cmr10'},
        '\\tensl': {'font': 'cmsl10', 'setter': 'tensl', 'source': 'cmsl10'},
        '\\tensy': {'font': 'cmsy10', 'setter': 'tensy', 'skewchar': 48, 'source': 'cmsy10'},
        '\\tentt': {'font': 'cmtt10', 'setter': 'tentt', 'source': 'cmtt10'},
        '\\textfont0': {'font': 'cmr10', 'source': 'cmr10'},
        '\\textfont1': {'font': 'cmmi10', 'skewchar': 127, 'source': 'cmmi10'},
        '\\textfont2': {'font': 'cmsy10', 'skewchar': 48, 'source': 'cmsy10'},
        '\\textfont3': {'font': 'cmex10', 'source': 'cmex10', 'used': 1},
        '\\textfont4': {'font': 'cmti10', 'source': 'cmti10'},
        '\\textfont5': {'font': 'cmsl10', 'source': 'cmsl10'},
        '\\textfont6': {'font': 'cmbx10', 'source': 'cmbx10'},
        '\\textfont7': {'font': 'cmtt10', 'source': 'cmtt10'},
        '\\theta': {'char': 274},
        '\\thickmuskip': {'control': 'thickmuskip', 'value': [327680, 327680, 0]},
        '\\thinmuskip': {'control': 'thinmuskip', 'value': [196608]},
        '\\thr@@': {'char': 3}, '\\times': {'char': 8706},
        '\\to': {'char': 12833},        '\\toks10': [['\\hfil']],
        '\\toks11': [['\\hss'], ['\\tenrm'], ['\\folio'], ['\\hss']],
        '\\toks@': {'register': '\\toks0'},
        '\\tolerance': {'control': 'tolerance', 'value': 200},
        '\\top': {'char': 574}, '\\topins': {'char': 253},
        '\\topskip': {'control': 'topskip', 'value': [655360]},
        '\\tracinglostchars': {'control': 'tracinglostchars', 'value': 1},
        '\\triangle': {'char': 564},    '\\triangleleft': {'char': 8495},
        '\\triangleright': {'char': 8494},      '\\ttfam': {'char': 7},
        '\\tw@': {'char': 2},   '\\uchyph': {'control': 'uchyph', 'value': 1},
        '\\uplus': {'char': 8797},      '\\upsilon': {'char': 285},
        '\\varepsilon': {'char': 290},  '\\varphi': {'char': 295},
        '\\varpi': {'char': 292},       '\\varrho': {'char': 293},
        '\\varsigma': {'char': 294},    '\\vartheta': {'char': 291},
        '\\vbadness': {'control': 'vbadness', 'value': 1000},
        '\\vdash': {'char': 12896},     '\\vee': {'char': 8799},
        '\\vfuzz': {'control': 'vfuzz', 'value': 6554},
        '\\voidb@x': {'char': 10},
        '\\vsize': {'control': 'vsize', 'value': 42152916},
        '\\wedge': {'char': 8798},
        '\\widowpenalty': {'control': 'widowpenalty', 'value': 150},
        '\\wp': {'char': 381},  '\\wr': {'char': 8815}, '\\xi': {'char': 280},
        '\\z@': {'register': '\\dimen12'},
        '\\z@skip': {'register': '\\skip12'},   '\\zeta': {'char': 272},
        }

# eof
